type: solution
name: test_blemesh_api
version: v7.4.3
description: ble sdk mesh api
license: Apache license v2.0
hw_info:                              #用户修改为对应board和chip
  cpu_id: cpu0
  board_name: phy6220_evb
  ld_script: ""

sdk_chip:
  - sdk_chip_phy6220: v7.4.3
depends:
  - cli: v7.4.3
  - ble_mesh: v7.4.3

def_config:
  CONFIG_KV_SMART: 1
  CONFIG_BT: 1
  CONFIG_CLI: 1
  CONFIG_KERNEL_RHINO: 1
  CONFIG_BT_L2CAP_RX_MTU: 31
  CONFIG_BT_L2CAP_TX_MTU: 31
  CONFIG_INIT_TASK_STACK_SIZE: 1024
  CONFIG_KERNEL_TIMER_STACK_SIZE: 1024
  CLI_CONFIG_STACK_SIZE: 1024
  CONFIG_BLE_MESH_PROV: 1
  CONFIG_BT_MESH_IV_UPDATE_TEST: 1
  CONFIG_BT_MESH_CFG_CLI: 1
  CONFIG_BT_MESH_GATT_PROXY: 1
  CONFIG_BT_MESH_HEALTH_CLI: 1
  CONFIG_BT_MESH_USE_SIG_MODEL: 1
  CONFIG_BT_MESH_MODEL_GEN_ONOFF_SRV: 1
  CONFIG_BT_MESH_MODEL_GEN_LEVEL_SRV: 1
  CONFIG_BT_MESH_MODEL_LIGHT_LIGHTNESS_SRV: 1
  CONFIG_BT_MESH_MODEL_LIGHT_CTL_SRV: 1
  CONFIG_BT_MESH_MODEL_GEN_ONOFF_CLI: 1
  CONFIG_BT_MESH_MODEL_GEN_LEVEL_CLI: 1
  CONFIG_BT_MESH_MODEL_LIGHT_LIGHTNESS_CLI: 1
  CONFIG_BT_MESH_MODEL_LIGHT_CTL_CLI: 1
  CONFIG_BT_MESH_MODEL_VENDOR_SRV: 1
  CONFIG_BT_MESH_MODEL_VENDOR_CLI: 1
  CONFIG_BOARD_PHY6220: 1
build_config:
  internal_include:
    - ""
  include:
    - app/include
    - app/src
  ldflag: -Wl,-ckmap="yoc.map" -Wl,-zmax-page-size=1024
source_file:
    - app/src/main.c
    - app/src/yunit_test_main.c
    - app/src/yunit.c
    - app/src/api_test.c
    - app/src/init/*.c
    - app/src/ble_sdk_mesh_test/*.c

link_config:
  path: ~
  library: ~
hidden: false
homepage: https://www.xrvm.cn