name: pangu_boot
version: v7.4.3                                     # <必选项> 组件版本号
description: BootLoader for pangu

type: solution

hw_info:
  cpu_id: cpu0
  chip_name: chip_pangu
  ld_script: gcc_flash.ld

depends:                                       # 该组件依赖其他的组件
  - csi: v7.4.3
  - chip_pangu: v7.4.3
  - boot: v7.4.3
  - partition: v7.4.3
  - sec_crypto: v7.4.3
  - key_mgr: v7.4.3

# 编译参数
build_config:
  internal_include:
    - board
  include:
    - app/include
  libs:
    - diff_dc_naf
    # - diff_dc_naf_dbg    # diff debug
  libpath: ""
  cflag: -g -Os -ffunction-sections -fdata-sections -Wpointer-arith -Wall -Wl,-EL -fno-inline-functions -nostdlib -fno-builtin -mistack -fno-strict-aliasing -fno-strength-reduce
  cxxflag: -g -Os -ffunction-sections -fdata-sections -Wpointer-arith -Wall -Wl,-EL -fno-inline-functions -nostdlib -fno-builtin -mistack -fno-strict-aliasing -fno-strength-reduce
  asmflag: ""
  ldflag: -Wl,-zmax-page-size=1024 -mhard-float -Wl,-ckmap="boot.map"


# 源文件
source_file:
  - app/src/*.c
  - porting/*.c
  - board/*.c

def_config:
  CONFIG_DEBUG: 2
  # CONFIG_MM_DETECT_ERROR: 1
  CONFIG_CLI_USART_BAUD: 115200
  # CONFIG_NO_OTA_UPGRADE: 1
  # CONFIG_OTA_NO_DIFF: 1
  CONFIG_PARITION_NO_VERIFY: 0
  # CONFIG_NOT_SUPORRT_SASC: 1
  CONFIG_TB_KP: 1
  CONFIG_EFUSE_SUPPORT: y
  CONFIG_MANTB_VERSION: 4
  CONFIG_NON_ADDRESS_FLASH: 1
  CONFIG_ARCH_INTERRUPTSTACK: 32768
  CONFIG_DISABLE_IRQ: 1

  CONFIG_ARCH_CSKY: 1
  CONFIG_KERNEL_WORKQUEUE: 1
  CONFIG_SYSTICK_HZ: 100
  CONFIG_CHIP_PANGU_CPU0: 1
  CONFIG_CHIP_PANGU: 1
  CONFIG_VENDOR_NAME: "xuantie"
  CONFIG_CPU: "ck804ef"
  # CONFIG_CPU_CK804EF: 1
  CONFIG_CSKY_CORETIM: 1
  CONFIG_HAVE_VIC: 1
  STDIO_UART: 1

  RSA_USING_ID2KEY: 1
  CONFIG_SYSTEM_SECURE: 1

  #sec_crypto
  #CONFIG_SEC_CRYPTO_AES_SW: 1
  #CONFIG_SEC_CRYPTO_SHA_SW: 1
  CONFIG_SEC_CRYPTO_RSA_SW: 1
  #CONFIG_SEC_CRYPTO_RNG_SW: 1