 /*
 * Copyright (C) 2017-2024 Alibaba Group Holding Limited
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include <perf_events.h>

char* perf_event_name[PMU_MHPM_EVENTS_MAX + 1] = {
    [PMU_HPM_L1_icache_Access                   ] = "l1-icache-access",
    [PMU_HPM_L1_icache_Miss                     ] = "l1-icache-miss",
    [PMU_HPM_iTLB_Miss                          ] = "itlb-miss",
    [PMU_HPM_D_UTLB_MISS                        ] = "d-utlb-miss",
    [PMU_HPM_jTLB_Miss                          ] = "jtlb-miss",
    [PMU_HPM_Condition_Branch_Mispred           ] = "condition-branch-mispred",
    [PMU_HPM_Condition_Branch                   ] = "condition-branch",
    [PMU_HPM_Indirect_Branch_Miss               ] = "indirect-branch-miss",
    [PMU_HPM_Indirect_Branch                    ] = "indirect-branch",
    [PMU_HPM_LSU_Spec_Fail                      ] = "lsu-spec-fail",
    [PMU_HPM_Store_Instruction                  ] = "store-instruction",
    [PMU_HPM_L1_dcache_load_access              ] = "l1-dcache-load-access",
    [PMU_HPM_L1_dcache_load_miss                ] = "l1-dcache-load-miss",
    [PMU_HPM_L1_dcache_store_access             ] = "l1-dcache-store-access",
    [PMU_HPM_L1_dcache_store_miss               ] = "l1-dcache-store-miss",
    [PMU_HPM_L2_Load_Access                     ] = "l2-load-access",
    [PMU_HPM_L2_Load_Miss                       ] = "l2-load-miss",
    [PMU_HPM_L2_Store_Access                    ] = "l2-store-access",
    [PMU_HPM_L2_Store_Miss                      ] = "l2-store-miss",
    [PMU_HPM_RF_Launch_Fail                     ] = "rf-launch-fail",
    [PMU_HPM_RF_Reg_Launch_Fail                 ] = "reg-launch-fail",
    [PMU_HPM_Issue_Instruction                  ] = "issue-instruction",
    [PMU_HPM_LSU_Cross_4K_Stall                 ] = "lsu-cross-4k-stall",
    [PMU_HPM_LSU_Other_Stall                    ] = "lsu-other-stall",
    [PMU_HPM_SQ_Discard                         ] = "sq-discard",
    [PMU_HPM_SQ_Data_Discard                    ] = "sq-data-discard",
    [PMU_HPM_IFU_Branch_Target_Mispred          ] = "ifu-branch-target-mispred",
    [PMU_HPM_IFU_Branch_Target_Instruction      ] = "ifu-branch-target-instruction",
    [PMU_HPM_ALU_Instruction                    ] = "alu-instruction",
    [PMU_HPM_Vector_SIMD_Instruction            ] = "vector-simd-instruction",
    [PMU_HPM_CSR_Instruction                    ] = "csr-instruction",
    [PMU_HPM_ATOMIC_Instruction                 ] = "atomic-instruction",
    [PMU_HPM_Interupt_Numer                     ] = "interupt-numer",
    [PMU_HPM_Environment_Call                   ] = "environment-call",
    [PMU_HPM_Long_Jump                          ] = "long-jump",
    [PMU_HPM_Stalled_Cycles_Frontend            ] = "stalled-cycles-frontend",
    [PMU_HPM_Stalled_Cycles_Backend             ] = "stalled-cycles-backend",
    [PMU_HPM_SYNC_Stall                         ] = "sync-stall",
    [PMU_HPM_Float_Point_Instruction            ] = "float-point-instruction",
    [PMU_HPM_M_Mode_Cycles                      ] = "m-mode-cycles",
    [PMU_HPM_S_Mode_Cycles                      ] = "s-mode-cycles",
    [PMU_HPM_U_Mode_Cycles                      ] = "u-mode-cycles",
    [PMU_HPM_Exception_Number                   ] = "exception-number",
    [PMU_HPM_Flush_Number                       ] = "flush-number",
    [PMU_HPM_LOAD_Instruction                   ] = "load-instruction",
    [PMU_HPM_Fused_Instruction                  ] = "fused-instruction",
    [PMU_HPM_MULT_Instruction                   ] = "mult-instruction",
    [PMU_HPM_DIV_Instruction                    ] = "div-instruction",
    [PMU_HPM_Mult_Inner_Forward                 ] = "mult-inner-forward",
    [PMU_HPM_DIV_Buffer_Hit                     ] = "div-buffer-hit",
    [PMU_HPM_Branch_Instruction                 ] = "branch-instruction",
    [PMU_HPM_Uncondition_Branch                 ] = "uncondition-branch",
    [PMU_HPM_Branch_Mispred                     ] = "branch-mispred",
    [PMU_HPM_Uncondition_Branch_Mispred         ] = "uncondition-branch-mispred",
    [PMU_HPM_Taken_Branch_Mispred               ] = "taken-branch-mispred",
    [PMU_HPM_Taken_Condition_Branch             ] = "taken-condition-branch",
    [PMU_HPM_Taken_Condition_Branch_Mispred     ] = "taken-condition-branch-mispred",
    [PMU_HPM_Unalign_LOAD_Instruction           ] = "unalign-load-instruction",
    [PMU_HPM_Unalign_STORE_Instruction          ] = "unalign-store-instruction",
    [PMU_HPM_LR_Instruction                     ] = "lr-instruction",
    [PMU_HPM_SC_Instruction                     ] = "sc-instruction",
    [PMU_HPM_AMO_Instruction                    ] = "amo-instruction",
    [PMU_HPM_Barrier_Instruction                ] = "barrier-instruction",
    [PMU_HPM_Failed_SC_Instruction              ] = "failed-sc-instruction",
    [PMU_HPM_Bus_Barrier                        ] = "bus-barrier",
    [PMU_HPM_FP_DIV_Instruction                 ] = "fp-div-instruction",
    [PMU_HPM_FP_LOAD_Instruction                ] = "fp-load-instruction",
    [PMU_HPM_FP_STORE_Instruction               ] = "fp-store-instruction",
    [PMU_HPM_Vector_DIV_Instruction             ] = "vector-div-instruction",
    [PMU_HPM_Vector_LOAD_Instruction            ] = "vector-load-instruction",
    [PMU_HPM_Vector_STORE_Instruction           ] = "vector-store-instruction",
    [PMU_HPM_Vector_Micro_Op                    ] = "vector-micro-op",
    [PMU_HPM_ECC_Interrupt                      ] = "ecc-interrupt",
    [PMU_HPM_Async_Abort_Interrupt              ] = "async-abort-interrupt",
    [PMU_HPM_IF_Stall                           ] = "if-stall",
    [PMU_HPM_IP_Stall                           ] = "ip-stall",
    [PMU_HPM_IB_Stall                           ] = "ib-stall",
    [PMU_HPM_IF_Refill_Stall                    ] = "if-refill-stall",
    [PMU_HPM_IF_Mmu_Stall                       ] = "if-mmu-stall",
    [PMU_HPM_IB_Mispred_Stall                   ] = "ib-mispred-stall",
    [PMU_HPM_IB_Fifo_Stall                      ] = "ib-fifo-stall",
    [PMU_HPM_IB_Ind_Btb_Rd_Stall                ] = "ib-ind-btb-rd-stall",
    [PMU_HPM_IB_Vsetvl_Stall                    ] = "ib-vsetvl-stall",
    [PMU_HPM_ID_Stall                           ] = "id-stall",
    [PMU_HPM_RF_Stall                           ] = "rf-stall",
    [PMU_HPM_EU_Stall                           ] = "eu-stall",
    [PMU_HPM_ID_Inst_Pipedown                   ] = "id-inst-pipedown",
    [PMU_HPM_RF_Inst_Pipedown                   ] = "rf-inst-pipedown",
    [PMU_HPM_ID_One_Inst_Pipedown               ] = "id-one-inst-pipedown",
    [PMU_HPM_ID_CSR_Before_Fence_Stall          ] = "id-csr-before-fence-stall",
    [PMU_HPM_ID_VSETVL_Fof_Stall                ] = "id-vsetvl-fof-stall",
    [PMU_HPM_ID_Flush_Stall                     ] = "id-flush-stall",
    [PMU_HPM_ID_Misprediction_Stall             ] = "id-misprediction-stall",
    [PMU_HPM_ID_IID_Not_Vld_Stall               ] = "id-iid-not-vld-stall",
    [PMU_HPM_RF_One_Inst_Pipedown               ] = "rf-one-inst-pipedown",
    [PMU_HPM_RF_RAW_Stall                       ] = "rf-raw-stall",
    [PMU_HPM_RF_WAW_Stall                       ] = "rf-waw-stall",
    [PMU_HPM_RF_Structure_Stall                 ] = "rf-structure-stall",
    [PMU_HPM_RF_CSR_After_Fence_Stall           ] = "rf-csr-after-fence-stall",
    [PMU_HPM_EU_IU_Full                         ] = "eu-iu-full",
    [PMU_HPM_EU_IU_Control_Full                 ] = "eu-iu-control-full",
    [PMU_HPM_EU_CP0_Full                        ] = "eu-cp0-full",
    [PMU_HPM_EU_LSU_LOAD_Full                   ] = "eu-lsu-load-full",
    [PMU_HPM_EU_LSU_STORE_Full                  ] = "eu-lsu-store-full",
    [PMU_HPM_EU_VFPU_Full                       ] = "eu-vfpu-full",
    [PMU_HPM_EU_BJU_Full                        ] = "eu-bju-full",
    [PMU_HPM_IU_Dp_Stall_Pipe0                  ] = "iu-dp-stall-pipe0",
    [PMU_HPM_IU_MULT_Stall_Pipe0                ] = "iu-mult-stall-pipe0",
    [PMU_HPM_IU_DIV_EX1_Stall_Pipe0             ] = "iu-div-ex1-stall-pipe0",
    [PMU_HPM_IU_Dp_Stall_Pipe1                  ] = "iu-dp-stall-pipe1",
    [PMU_HPM_IU_MULT_Stall_Pipe1                ] = "iu-mult-stall-pipe1",
    [PMU_HPM_IU_DIV_EX1_Stall_Pipe1             ] = "iu-div-ex1-stall-pipe1",
    [PMU_HPM_IU_DP_Wb_Conflict_Pipe0            ] = "iu-dp-wb-conflict-pipe0",
    [PMU_HPM_IU_DP_WAW_Stall_Pipe0              ] = "iu-dp-waw-stall-pipe0",
    [PMU_HPM_IU_DP_Uncommit_Pipe0               ] = "iu-dp-uncommit-pipe0",
    [PMU_HPM_IU_DP_Wb_Conflict_Pipe1            ] = "iu-dp-wb-conflict-pipe1",
    [PMU_HPM_IU_DP_WAW_Stall_Pipe1              ] = "iu-dp-waw-stall-pipe1",
    [PMU_HPM_IU_DP_Uncommit_Pipe1               ] = "iu-dp-uncommit-pipe1",
    [PMU_HPM_IU_MULT_Uncommit                   ] = "iu-mult-uncommit",
    [PMU_HPM_IU_MULT_Wb_Stall                   ] = "iu-mult-wb-stall",
    [PMU_HPM_IU_DIV_Uncommit                    ] = "iu-div-uncommit",
    [PMU_HPM_IU_DIV_Wb_Stall                    ] = "iu-div-wb-stall",
    [PMU_HPM_LSU_LOAD_WAW_Stall                 ] = "lsu-load-waw-stall",
    [PMU_HPM_LSU_LOAD_Commit_Stall              ] = "lsu-load-commit-stall",
    [PMU_HPM_LSU_LOAD_RAW_Stall                 ] = "lsu-load-raw-stall",
    [PMU_HPM_LSU_STORE_Commit_Stall             ] = "lsu-store-commit-stall",
    [PMU_HPM_Vidu_Rf_No_Pipedown                ] = "vidu-rf-no-pipedown",
    [PMU_HPM_VPU_Stall_Pipe0                    ] = "vpu-stall-pipe0",
    [PMU_HPM_VPU_Stall_Pipe1                    ] = "vpu-stall-pipe1",
    [PMU_HPM_VPU_Struct_Hazard_Stall_Pipe0      ] = "vpu-struct-hazard-stall-pipe0",
    [PMU_HPM_VPU_Uncommit_Stall_Pipe0           ] = "vpu-uncommit-stall-pipe0",
    [PMU_HPM_VPU_VLSU_Stall_Pipe0               ] = "vpu-vlsu-stall-pipe0",
    [PMU_HPM_VPU_Struct_Hazard_Stall_Pipe1      ] = "vpu-struct-hazard-stall-pipe1",
    [PMU_HPM_VPU_Uncommit_Stall_Pipe1           ] = "vpu-uncommit-stall-pipe1",
    [PMU_HPM_VPU_VLSU_Stall_Pipe1               ] = "vpu-vlsu-stall-pipe1",
    [PMU_HPM_VFPU_FDIV                          ] = "vfpu-fdiv/vdiv-busy",
    [PMU_HPM_BJU_CP0_Stall                      ] = "bju-cp0-stall",
    [PMU_HPM_BJU_IBUF_Stall                     ] = "bju-ibuf-stall",
    [PMU_HPM_BJU_Wb_Stall                       ] = "bju-wb-stall",
    [PMU_HPM_BJU_Pipedown_Stall                 ] = "bju-pipedown-stall",
    [PMU_HPM_RTU_Flush                          ] = "rtu-flush",
    [PMU_HPM_RTU_IU_Not_No_OP                   ] = "rtu-iu-not-no-op",
    [PMU_HPM_RTU_BJU_Not_No_OP                  ] = "rtu-bju-not-no-op",
    [PMU_HPM_RTU_LSU_Not_No_OP                  ] = "rtu-lsu-not-no-op",
    [PMU_HPM_RTU_CP0_Not_No_OP                  ] = "rtu-cp0-not-no-op",
    [PMU_HPM_RTU_VFPU_Not_No_OP                 ] = "rtu-vfpu-not-no-op",
    [PMU_HPM_RTU_Only_IU_Not_No_OP              ] = "rtu-only-iu-not-no-op",
    [PMU_HPM_RTU_Only_BJU_Not_No_OP             ] = "rtu-only-bju-not-no-op",
    [PMU_HPM_RTU_Only_LSU_Not_No_OP             ] = "rtu-only-lsu-not-no-op",
    [PMU_HPM_RTU_Only_CP0_Not_No_OP             ] = "rtu-only-cp0-not-no-op",
    [PMU_HPM_RTU_Only_VFPU_Not_No_OP            ] = "rtu-only-vfpu-not-no-op",
    [PMU_HPM_L1_Dcache_Access                   ] = "l1-dcache-access",
    [PMU_HPM_L1_Dcache_Miss                     ] = "l1-dcache-miss",
    [PMU_HPM_L1_Dcache_Exclusive_Eviction       ] = "l1-dcache-exclusive-eviction",
    [PMU_HPM_Icache_Prefetch                    ] = "icache-prefetch",
    [PMU_HPM_Dcache_Amr_Active                  ] = "dcache-amr-active",
    [PMU_HPM_Icache_Prefetch_Miss               ] = "icache-prefetch-miss",
    [PMU_HPM_Dcache_Refill_Casued_by_Prefetch   ] = "dcache-refill-casued-by-prefetch",
    [PMU_HPM_Dcache_Hit_Caused_by_Prefetch      ] = "dcache-hit-caused-by-prefetch",
    [PMU_HPM_Store_Dtlb_Miss                    ] = "store-dtlb-miss",
    [PMU_HPM_Load_Dtlb_Miss                     ] = "load-dtlb-miss",
    [PMU_HPM_L2_Access                          ] = "l2-access",
    [PMU_HPM_L2_Miss                            ] = "l2-miss",
    [PMU_HPM_Snb_Read_Create_Vld                ] = "snb-read-create-vld",
    [PMU_HPM_Snb_Read_Create_Stall              ] = "snb-read-create-stall",
    [PMU_HPM_Snb_Write_Create_Vld               ] = "snb-write-create-vld",
    [PMU_HPM_Snb_Write_Create_Stall             ] = "snb-write-create-stall",
    [PMU_HPM_Iq_Full                            ] = "iq-full",
    [PMU_HPM_Vidu_Vec0_Stall                    ] = "vidu-vec0-stall",
    [PMU_HPM_Vidu_Vec1_Stall                    ] = "vidu-vec1-stall",
    [PMU_HPM_Vidu_Vec0_Depend_Stall             ] = "vidu-vec0-depend-stall",
    [PMU_HPM_Vidu_Vec0_Struct_Hazard_Stall      ] = "vidu-vec0-struct-hazard-stall",
    [PMU_HPM_Vidu_Vec1_Depend_Stall             ] = "vidu-vec1-depend-stall",
    [PMU_HPM_Vidu_Vec1_Struct_Hazard_Stall      ] = "vidu-vec1-struct-hazard-stall",
    [PMU_HPM_Vidu_Total_Cycle                   ] = "vidu-total-cycle",
    [PMU_HPM_Vidu_Vec0_Cycle                    ] = "vidu-vec0-cycle",
    [PMU_HPM_Vidu_Vec1_Cycle                    ] = "vidu-vec1-cycle",
};

#if defined(CONFIG_PMU_EVENTS_FIXED)

uint8_t counters_idx_fixed[CONFIG_NR_HPM_EVENT_FIXED] = {
    [PMU_HPM_L1_icache_Access             ] = 3,
    [PMU_HPM_L1_icache_Miss               ] = 4,
    [PMU_HPM_iTLB_Miss                    ] = 5,
    [PMU_HPM_D_UTLB_MISS                  ] = 6,
    [PMU_HPM_jTLB_Miss                    ] = 7,
    [PMU_HPM_Condition_Branch_Mispred     ] = 8,
    [PMU_HPM_Condition_Branch             ] = 9,
    [PMU_HPM_Indirect_Branch_Miss         ] = 10,
    [PMU_HPM_Indirect_Branch              ] = 11,
    [PMU_HPM_LSU_Spec_Fail                ] = 12,
    [PMU_HPM_Store_Instruction            ] = 13,
    [PMU_HPM_L1_dcache_load_access        ] = 14,
    [PMU_HPM_L1_dcache_load_miss          ] = 15,
    [PMU_HPM_L1_dcache_store_access       ] = 16,
    [PMU_HPM_L1_dcache_store_miss         ] = 17,
    [PMU_HPM_L2_Load_Access               ] = 18,
    [PMU_HPM_L2_Load_Miss                 ] = 19,
    [PMU_HPM_L2_Store_Access              ] = 20,
    [PMU_HPM_L2_Store_Miss                ] = 21,
    [PMU_HPM_RF_Launch_Fail               ] = 22,
    [PMU_HPM_RF_Reg_Launch_Fail           ] = 23,
    [PMU_HPM_Issue_Instruction            ] = 24,
    [PMU_HPM_LSU_Cross_4K_Stall           ] = 25,
    [PMU_HPM_LSU_Other_Stall              ] = 26,
    [PMU_HPM_SQ_Discard                   ] = 27,
    [PMU_HPM_SQ_Data_Discard              ] = 28,
    [PMU_HPM_IFU_Branch_Target_Mispred    ] = 29,
    [PMU_HPM_IFU_Branch_Target_Instruction] = 30,
    [PMU_HPM_ALU_Instruction              ] = 31,
};

uint16_t events_fixed[CONFIG_NR_HPM_EVENT_FIXED] = {
    PMU_HPM_L1_icache_Access,
    PMU_HPM_L1_icache_Miss,
    PMU_HPM_iTLB_Miss,
    PMU_HPM_D_UTLB_MISS,
    PMU_HPM_jTLB_Miss,
    PMU_HPM_Condition_Branch_Mispred,
    PMU_HPM_Condition_Branch,
    PMU_HPM_Indirect_Branch_Miss,
    PMU_HPM_Indirect_Branch,
    PMU_HPM_LSU_Spec_Fail,
    PMU_HPM_Store_Instruction,
    PMU_HPM_L1_dcache_load_access,
    PMU_HPM_L1_dcache_load_miss,
    PMU_HPM_L1_dcache_store_access,
    PMU_HPM_L1_dcache_store_miss,
    PMU_HPM_L2_Load_Access,
    PMU_HPM_L2_Load_Miss,
    PMU_HPM_L2_Store_Access,
    PMU_HPM_L2_Store_Miss,
    PMU_HPM_RF_Launch_Fail,
    PMU_HPM_RF_Reg_Launch_Fail,
    PMU_HPM_Issue_Instruction,
    PMU_HPM_LSU_Cross_4K_Stall,
    PMU_HPM_LSU_Other_Stall,
    PMU_HPM_SQ_Discard,
    PMU_HPM_SQ_Data_Discard,
    PMU_HPM_IFU_Branch_Target_Mispred,
    PMU_HPM_IFU_Branch_Target_Instruction,
    PMU_HPM_ALU_Instruction,
};

#endif //  CONFIG_PMU_EVENTS_FIXED
