
## 第一部分： 基础信息
name: opus                                          # <必选项> 包名称 （符合C语言变量命名规则），长度少于等于64字节
version: v7.9.0                                    # <必选项> 组件版本号
description: Opus是一个完全开放的、免费的、多功能的音频编解码器。 它在交互式的语音和音乐在互联网中的传输方面有着无与伦比的优势，但是同样致力于存储和流媒体应用程序。 # <必选项> 建议至少20字以上
type: common                                        # <必选项> 组件类型，为：solution, chip, board, common, sdk
tag: 多媒体播放器                                   # <可选项> 组件分类，缺省值： ''
keywords:                                           # <可选项> 标签，会影响到组件被搜索的效果，合理的标签很重要
  - opus
  - audio decoder & encoder
  - media
license: Xiph.Org                                   # <可选项> 源代码的许可证，要确保所有代码、文件的许可证不冲突。如：MIT，Apache license v2.0，BSD

## 第二部分：依赖信息
#           指定该组件依赖的组件及版本
# sdk_chip:                                # <可选项> 该组件依赖sdk组件，合理的依赖才能保证组件能编译、使用
#   - sdk_chip_csky_dummy: v7.4.0
#   - sdk_chip_riscv_dummy: v7.4.0
# depends:                                 # <可选项> 该组件依赖其他的组件，合理的依赖才能保证组件能编译、使用
#   - minilibc: v7.4.0
#   - aos: v7.4.0

## 第四部分：编译连接信息
# build_config:                            # <可选项> 编译配置项
#   include:                               # <可选项> 编译时，影响编译器的-I 参数 ,全局有效
#     - src                                #        include 只能是该软件包下的目录，不能使用外部目录
#   internal_include:                      # <可选项> 编译时，影响编译器的-I 参数 ,组件内有效
#     - include
#   cflag: ''                              # <可选项> C 编译器所需要要的编译参数
#   cxxflag: ''                            # <可选项> CXX 编译器所需要要的编译参数
#   asmflag: ''                            # <可选项> 汇编器所需要要参数
#   define:                                # <可选项> 宏定义, 增加编译器的-D 选项,如：
#     XXX: 1                               #   -DXXX=1
#     AAA: 1                               #   -DAAA
#     STR: "abc"                           #   -DSTR="abc"
#   libs:                                  # 该组件中支持的二进制静态库,如：libxxx.a, libyyy.a
#     - xxx                                #   -lxxx
#     - yyy                                #   -lyyy
#   libpath:                               # 指定静态库所在的路径（相对于该组件路径）
#     - libs                               #   -Llibs
build_config:
  cflag: ' -Wall -O2  -Wno-unused-function'
  define:
    - HAVE_CONFIG_H
    - FIXED_POINT
    - OPUS_CSKY_ASM
  include:
    - include
  internal_include:
    - src/.
    - src/celt
    - src/silk
    - src/silk/float
    - src/silk/fixed
    - include/opus

# source_file:                             # <可选项> 指定参与编译的源代码文件，支持通配符，采用相对路径
#   - src/*.c                              # 例：组件 src 目录下所有的扩展名为 c 的源代码文件
source_file:
  - "src/celt/bands.c"
  - "src/celt/celt.c"
  - "src/celt/celt_encoder.c"
  - "src/celt/celt_decoder.c"
  - "src/celt/cwrs.c"
  - "src/celt/entcode.c"
  - "src/celt/entdec.c"
  - "src/celt/entenc.c"
  - "src/celt/kiss_fft.c"
  - "src/celt/laplace.c"
  - "src/celt/mathops.c"
  - "src/celt/mdct.c"
  - "src/celt/modes.c"
  - "src/celt/pitch.c"
  - "src/celt/celt_lpc.c"
  - "src/celt/quant_bands.c"
  - "src/celt/rate.c"
  - "src/celt/vq.c"
  - "src/silk/CNG.c"
  - "src/silk/code_signs.c"
  - "src/silk/init_decoder.c"
  - "src/silk/decode_core.c"
  - "src/silk/decode_frame.c"
  - "src/silk/decode_parameters.c"
  - "src/silk/decode_indices.c"
  - "src/silk/decode_pulses.c"
  - "src/silk/decoder_set_fs.c"
  - "src/silk/dec_API.c"
  - "src/silk/enc_API.c"
  - "src/silk/encode_indices.c"
  - "src/silk/encode_pulses.c"
  - "src/silk/gain_quant.c"
  - "src/silk/interpolate.c"
  - "src/silk/LP_variable_cutoff.c"
  - "src/silk/NLSF_decode.c"
  - "src/silk/NSQ.c"
  - "src/silk/NSQ_del_dec.c"
  - "src/silk/PLC.c"
  - "src/silk/shell_coder.c"
  - "src/silk/tables_gain.c"
  - "src/silk/tables_LTP.c"
  - "src/silk/tables_NLSF_CB_NB_MB.c"
  - "src/silk/tables_NLSF_CB_WB.c"
  - "src/silk/tables_other.c"
  - "src/silk/tables_pitch_lag.c"
  - "src/silk/tables_pulses_per_block.c"
  - "src/silk/VAD.c"
  - "src/silk/control_audio_bandwidth.c"
  - "src/silk/quant_LTP_gains.c"
  - "src/silk/VQ_WMat_EC.c"
  - "src/silk/HP_variable_cutoff.c"
  - "src/silk/NLSF_encode.c"
  - "src/silk/NLSF_VQ.c"
  - "src/silk/NLSF_unpack.c"
  - "src/silk/NLSF_del_dec_quant.c"
  - "src/silk/process_NLSFs.c"
  - "src/silk/stereo_LR_to_MS.c"
  - "src/silk/stereo_MS_to_LR.c"
  - "src/silk/check_control_input.c"
  - "src/silk/control_SNR.c"
  - "src/silk/init_encoder.c"
  - "src/silk/control_codec.c"
  - "src/silk/A2NLSF.c"
  - "src/silk/ana_filt_bank_1.c"
  - "src/silk/biquad_alt.c"
  - "src/silk/bwexpander_32.c"
  - "src/silk/bwexpander.c"
  - "src/silk/debug.c"
  - "src/silk/decode_pitch.c"
  - "src/silk/inner_prod_aligned.c"
  - "src/silk/lin2log.c"
  - "src/silk/log2lin.c"
  - "src/silk/LPC_analysis_filter.c"
  - "src/silk/LPC_inv_pred_gain.c"
  - "src/silk/table_LSF_cos.c"
  - "src/silk/NLSF2A.c"
  - "src/silk/NLSF_stabilize.c"
  - "src/silk/NLSF_VQ_weights_laroia.c"
  - "src/silk/pitch_est_tables.c"
  - "src/silk/resampler.c"
  - "src/silk/resampler_down2_3.c"
  - "src/silk/resampler_down2.c"
  - "src/silk/resampler_private_AR2.c"
  - "src/silk/resampler_private_down_FIR.c"
  - "src/silk/resampler_private_IIR_FIR.c"
  - "src/silk/resampler_private_up2_HQ.c"
  - "src/silk/resampler_rom.c"
  - "src/silk/sigm_Q15.c"
  - "src/silk/sort.c"
  - "src/silk/sum_sqr_shift.c"
  - "src/silk/stereo_decode_pred.c"
  - "src/silk/stereo_encode_pred.c"
  - "src/silk/stereo_find_predictor.c"
  - "src/silk/stereo_quant_pred.c"
  - "src/silk/LPC_fit.c"
  - "src/src/opus.c"
  - "src/src/opus_decoder.c"
  - "src/src/opus_encoder.c"
  - "src/src/opus_multistream.c"
  - "src/src/opus_multistream_encoder.c"
  - "src/src/opus_multistream_decoder.c"
  - "src/src/repacketizer.c"
  - "src/src/opus_projection_encoder.c"
  - "src/src/opus_projection_decoder.c"
  - "src/src/mapping_matrix.c"
  - "src/src/analysis.c"
  - "src/src/mlp.c"
  - "src/src/mlp_data.c"
  - "src/silk/fixed/LTP_analysis_filter_FIX.c"
  - "src/silk/fixed/LTP_scale_ctrl_FIX.c"
  - "src/silk/fixed/corrMatrix_FIX.c"
  - "src/silk/fixed/encode_frame_FIX.c"
  - "src/silk/fixed/find_LPC_FIX.c"
  - "src/silk/fixed/find_LTP_FIX.c"
  - "src/silk/fixed/find_pitch_lags_FIX.c"
  - "src/silk/fixed/find_pred_coefs_FIX.c"
  - "src/silk/fixed/noise_shape_analysis_FIX.c"
  - "src/silk/fixed/process_gains_FIX.c"
  - "src/silk/fixed/regularize_correlations_FIX.c"
  - "src/silk/fixed/residual_energy16_FIX.c"
  - "src/silk/fixed/residual_energy_FIX.c"
  - "src/silk/fixed/warped_autocorrelation_FIX.c"
  - "src/silk/fixed/apply_sine_window_FIX.c"
  - "src/silk/fixed/autocorr_FIX.c"
  - "src/silk/fixed/burg_modified_FIX.c"
  - "src/silk/fixed/k2a_FIX.c"
  - "src/silk/fixed/k2a_Q16_FIX.c"
  - "src/silk/fixed/pitch_analysis_core_FIX.c"
  - "src/silk/fixed/vector_ops_FIX.c"
  - "src/silk/fixed/schur64_FIX.c"
  - "src/silk/fixed/schur_FIX.c"

## 第五部分：配置信息
# def_config:                              # 组件的可配置项
#   CONFIG_DEBUG: y
#   CONFIG_PARAM_NOT_CHECK: y
#   CONFIG_CLI: y

## 第六部分：安装信息
# install:
#   - dest: include/                       # 安装的目的路径 dest是相对路径，通常是相对于YoC SDK 安装目录
#     source:                              # 安装源列表
#      - src/*.h                           # 支持通配符，相对路径
install:
  - dest: "include/opus"
    source:
      - "include/opus/*.h"

## 第七部分：导出部分
# export:
#   - dest: "<SOLUTION_PATH>/generated/data" # 安装的目的路径 dest是相对路径
#     source:                                # 安装源列表
#       - "bootimgs/boot"
#       - "bootimgs/tee"
#       - "bootimgs/mtb"
#       - "configs/config.yaml"
