
## 第一部分： 基础信息
name: yocopen                                        # <必选项> 包名称 （符合C语言变量命名规则），长度少于等于64字节
version: v8.0.0                                     # <必选项> 组件版本号
description: YoC组件集合                             # <必选项> 建议至少20字以上
type: common                                         # <必选项> 组件类型，为：solution, chip, board, common, sdk
tag: 核心模块                                        # <可选项> 组件分类，缺省值： ''
license: Apache license v2.0                         # <可选项> 源代码的许可证，要确保所有代码、文件的许可证不冲突。如：MIT，Apache license v2.0，BSD

## 第二部分：依赖信息
#           指定该组件依赖的组件及版本，版本支持条件比较，支持：>=v1.0, >v1.0, ==v1.0, <=v1.0, <v1.0, v1.0
#           未指定条件时，默认为 ==，如 v1.0 与 ==v1.0
# depends:                                 # <可选项> 该组件依赖其他的组件，合理的依赖才能保证组件能编译、使用
#   - minilibc: v7.2.0
#   - aos: >=v7.2.0
depends:
  # base component
  - yoc_base: v8.0.0
  - rhino: v8.0.0
  - rhino_arch: v8.0.0
  - rhino_pwrmgmt: v8.0.0
  - freertos: v8.0.0
  - rtthread: v8.0.0
  - minilibc: v8.0.0
  - libc_stub: v8.0.0
  - posix: v8.0.0
  - ipc: v8.0.0
  - log_ipc: v8.0.0

  # boot
  - boot: v8.0.0
  - bootab: v8.0.0

  # fastboot
  - excore: v8.0.0

  # cpu sdk
  - xuantie_cpu_sdk: v8.0.0

  # network
  - lwip: v8.0.0
  - sal: v8.0.0
  - ntp: v8.0.0
  - sntp: v8.0.0
  - netmgr: v8.0.0
  - httpclient: v8.0.0
  - transport: v8.0.0
  - websocket: v8.0.0
  - fota: v8.0.0
  - wifi_provisioning: v8.0.0

  # audio media
  - minialsa: v8.0.0
  - pvmp3dec: v8.0.0
  - record: v8.0.0
  - av: v8.0.0
  - av_cp: v8.0.0
  - amrnb: v8.0.0
  - amrwb: v8.0.0
  - speexdsp: v8.0.0
  - flac: v8.0.0
  - speex: v8.0.0
  - sonic: v8.0.0
  - opus: v8.0.0
  - ogg: v8.0.0
  - smart_audio: v8.0.0

  # fs
  - vfs: v8.0.0
  - devfs: v8.0.0
  - littlefs: v8.0.0
  - fatfs: v8.0.0
  - lwext4: v8.0.0

  # security
  - mbedtls: v8.0.0
  - key_mgr: v8.0.0
  - sec_crypto: v8.0.0
  - se: v8.0.0

  # bluetooth
  - ble_mesh: v8.0.0
  - ble_host: v8.0.0

  # zip
  - zlib: v8.0.0
  - xz: v8.0.0

  # utils
  - cmsis: v8.0.0
  - at: v8.0.0
  - ers: v8.0.0
  - button: v8.0.0
  - clock_alarm: v8.0.0
  - cjson: v8.0.0
  - fct: v8.0.0
  - dut_service: v8.0.0
  - adb: v8.0.0
  - csi2d: v8.0.0

  # Ali Tmall app
  - smartliving: v8.0.0
  - breeze: v8.0.0

  # device drivers
  - drv_bt_rtl8723ds: v8.0.0
  - drv_wifi_rtl8723ds: v8.0.0
  - drv_sdmmc: v8.0.0
  - drv_leds: v8.0.0    # no use
  - drv_light: v8.0.0
  - drv_snd_bl606p: v8.0.0

  # chip
  - chip_riscv_dummy: v8.0.0
  - chip_ch2601: v8.0.0
  - chip_d1: v8.0.0
  - chip_bl606p: v8.0.0

  # boards
  - board_riscv_dummy: v8.0.0
  - ch2601_evb: v8.0.0
  - d1_dockpro_evb: v8.0.0
  - bl606p_evb_e907: v8.0.0
  - bl606p_evb_c906: v8.0.0

  # chip sdk
  - sdk_chip_riscv_dummy: v8.0.0
  - sdk_chip_ch2601: v8.0.0
  - sdk_chip_d1: v8.0.0
  - sdk_chip_bl606p_e907: v8.0.0

  # common demo
  - helloworld: v8.0.0
  - fota_demo: v8.0.0
  - wifi_demo: v8.0.0
  - httpclient_demo: v8.0.0
  - kv_demo: v8.0.0
  - cli_demo: v8.0.0
  - xplayer_demo: v8.0.0
  - codec_demo: v8.0.0
  - devices_demo: v8.0.0
  - ipc_demo: v8.0.0
  - led_demo: v8.0.0
  - display_drv_demo: v8.0.0
  - usb_demo: v8.0.0
  - gprs_demo: v8.0.0
  - fs_demo: v8.0.0
  - secure_demo: v8.0.0
  - cpp_demo: v8.0.0
  - ble_uart_profile_server_demo: v8.0.0
  - ble_uart_profile_client_demo: v8.0.0
  - ble_shell_demo: v8.0.0
  - ble_scanner_demo: v8.0.0
  - ble_ibeacon_demo: v8.0.0
  - ble_hrs_demo: v8.0.0
  - ble_hid_keyboard_demo: v8.0.0
  - ble_dis_demo: v8.0.0
  - ble_bas_demo: v8.0.0
  - ble_advertising_demo: v8.0.0
  - mesh_shell: v8.0.0
  - mesh_switch_node_demo: v8.0.0
  - mesh_light_node_demo: v8.0.0
  - ble_ibeacon_apple_demo: v8.0.0
  # ch2601 demo
  - ch2601_boot: v8.0.0
  # bl606p demo
  - bl606p_boot: v8.0.0
  - bl606p_e907_coremark: v8.0.0
  - bl606p_e907_dhrystone: v8.0.0
  - bl606p_c906_ipc_demo: v8.0.0
  # d1 demo
  - d1_boot_demo: v8.0.0
  - d1_button_demo: v8.0.0

  # test
  #- sdk_test_solutions: v8.0.0
