name: test_csi1
version: v7.4.3
hw_info:
  cpu_id: ""
  cpu_name: ""
  vendor_name: ""
  chip_name: ""
  board_name: cb2201
  ld_script: ""
  flash_program: ""
name: csi10
description: csi10 test solution
tag: ""
keywords:
  - cb2201
  - solution
author:
  name: feimi
license: Apache license v2.0
homepage: https://www.xrvm.cn
type: solution
depends:
  - aos: v7.4.3
  - aos_hal: v7.4.3
  - cb2201: v7.4.3
  - chip_ch2201: v7.4.3
#  - console: v7.4.3
  - rhino_pwrmgmt: v7.4.3
  - csi: v7.4.3
  - hal_csi: v7.4.3
  - cli: v7.4.3
#  - drivers: v7.4.3
  - ulog: v7.4.3
  - minilibc: v7.4.3
  - rhino: v7.4.3
  - rhino_arch: v7.4.3
build_config:
  include:
    - app/include
    - app/include/csi/atserver
    - app/include/csi/common
    - app/include/csi/driver
  internal_include: ~
  cflag: -O0   -Wall
  cxxflag: -O0   -Wall
  asmflag: ""
  define:
    - ""
  libs: ~
  libpath: ~
  ldflag: -Wl,-ckmap="yoc.map" -Wl,-zmax-page-size=1024
source_file:
  - app/src/app_main.c
  - app/src/driver_tests_main.c 
  - app/src/init/*.c
  - app/src/csi/common/*.c 
  - app/src/csi/atserver/*.c 
  - app/src/csi/driver/dma/*.c ? <CONFIG_DMA>
  - app/src/csi/driver/gpio/*.c ? <CONFIG_GPIO>
  - app/src/csi/driver/iic/*.c ? <CONFIG_IIC>
  - app/src/csi/driver/pinmux/*.c 
  - app/src/csi/driver/pwm/*.c ? <CONFIG_PWM>
  - app/src/csi/driver/rtc/*.c ? <CONFIG_RTC>
  - app/src/csi/driver/spi/*.c ? <CONFIG_SPI>
  - app/src/csi/driver/spiflash/*.c ? <CONFIG_SPIFLASH>
  - app/src/csi/driver/timer/*.c ? <CONFIG_TIMER>
  - app/src/csi/driver/uart/*.c ? <CONFIG_UART>
  - app/src/csi/driver/wdt/*.c ? <CONFIG_WDT>
  - app/src/csi/driver/aes/*.c ? <CONFIG_AES>
  - app/src/csi/driver/adc/*.c ? <CONFIG_ADC>
def_config:
  CONFIG_ARCH_INTERRUPTSTACK: 1024
  CONFIG_CLI: 1
  CONFIG_DEBUG: 3
  CONFIG_TEE_CA: 1
#  CONFIG_SYSTEM_SECURE: 1
  CONFIG_INIT_TASK_STACK_SIZE: 2048
#  CONFIG_UART: 1
  CONFIG_WDT: 1
#  CONFIG_TIMER: 1
#  CONFIG_GPIO: 1
#  CONFIG_AES: 1
#  CONFIG_DMA: 1
#  CONFIG_IIC: 1
#  CONFIG_PWM: 1
#  CONFIG_RTC: 1
#  CONFIG_SPI: 1
#  CONFIG_SPIFLASH: 1
#  CONFIG_ADC: 1
# CONFIG_KERNEL_NONE: 1
