name: ch2601_freertos_demo
version: v7.4.3                                     # <必选项> 组件版本号
description: YoC helloworld SDK

type: solution

hw_info:
  cpu_id: cpu0
  board_name: ch2601_evb
  # board_name: board_dummy
  # toolchain_prefix: csky-abiv2-elf
  # cpu_name: CK805EF
  # vendor_name: xuantie
  # chip_name: 'chip_ch2201'
  # ld_script: configs/gcc_eflash.ld.S

depends:                                       # 该组件依赖其他的组件
  - csi: v7.4.3
  - freertos: v7.4.0
  - hal_csi: v7.4.6
  - aos_hal: v7.4.3
  - chip_ch2601: v7.4.3
  - ch2601_evb: v7.4.4
  # - kv: v7.4.3
  - partition: v7.4.5
  - aos: v7.4.5
  - newlib: v7.4.3
  - drivers: v7.4.5
  - uservice: v7.4.3
  - ulog: v7.4.3
  - sec_crypto: v7.4.3


# 编译参数
build_config:
  include:
    - app/include
    - app/src/oled
  cflag: -mno-ldr -mno-ext -mno-mula -mno-srri -mno-ldi -mno-addsl -mno-ldd -mno-rev -mno-condmv
  ldflag: -Wl,-Map="yoc.map" -Wl,-zmax-page-size=1024

# 源文件
source_file:
  # - app/src/init/cli_cmd.c
  - app/src/init/init.c
  - app/src/main.c
  - app/src/oled/*.c

def_config:
  CONFIG_CSI_V2: 1
  CONFIG_ARCH_INTERRUPTSTACK: 6144
  CONFIG_XIP: 1
  CONFIG_CLI: 1
  CONFIG_DEBUG: 1
  # CONFIG_SUPPORT_TSPEND: 1
  CONFIG_CPU_E906: 1
