## 第一部分： 基础信息
name: mesh_provisioner_demo
version: v8.0.0
description: YoC MESH Provisioner Demo
type: solution
## 第二部分：依赖信息
#           指定该组件依赖的组件及版本，版本支持条件比较，支持：>=v1.0, >v1.0, ==v1.0, <=v1.0, <v1.0, v1.0
#           未指定条件时，默认为 ==，如 v1.0 与 ==v1.0
# depends:                                 # <可选项> 该组件依赖其他的组件，合理的依赖才能保证组件能编译、使用
#   - minilibc: v7.2.0
#   - aos: >=v7.2.0
sdk_chip:
  - sdk_chip_d1: v8.0.0
mkflash_script: mkflash.sh
depends:
  - sdk_chip_d1: v8.0.0
  - ble_mesh: v8.0.0
  - gateway_mgmt: v8.0.0
  - tsl_engine: v8.0.0
  - httpclient: v8.0.0
  - ers: v8.0.0
  - ota_module: v8.0.0
  - cjson: v8.0.0
  - duktape: v8.0.0
  - smartliving: v8.0.0
  - mbedtls: v8.0.0
  - vfs: v8.0.0
  - transport: v8.0.0
  - at: v8.0.0
  - wifi_provisioning: v8.0.0
#  - button: v7.4.7
#  - dut_service: v7.4.4
## 第三部分：板级信息
# hw_info:                                 # 对 solution、board、chip 三个字段的改进，统称为 hw_info 字段
#   cpu_id: cpu0
#   cpu_name: CK804EF
#   vendor_name: xuantie
#   chip_name: chip_pangu                  # <可选项> 指定芯片组件名,未设置时，使用depends中 chip 第一个组件
#   board_name: pangu_cpu0                 # <可选项> 指定开发板组件名，未设置时，使用depends中 board 第一个组件
#   ld_script: configs/gcc_eflash.ld       # <可选项> 连接时使用 LD 脚本，当选把未设置时，使用对应的 board 的 LD 脚本
#   flash_program: bin/flash_program.elf   # <可选项> 芯片全局烧写程序
#   toolchain_prefix: csky-abiv2-elf       # <可选项> 编译器前缀
#   cpu0:
#     cpu_name: CK804EF                    # <必选项> 该芯片使用的 CPU 型号
#     ld_script: configs/gcc_eflash.ld     # <必选项> 连接时使用 LD 脚本
#     flash_program: bin/flash_program.elf # <可选项> 该CPU对应烧写程序，未指定时使用全局烧写程序
#     toolchain_prefix: csky-abiv2-elf     # <可选项> 编译器前缀
#   cpu1:
#     cpu_name: CK804EF                    # <必选项> 该芯片使用的 CPU 型号
#     ld_script: configs/gcc_eflash.ld     # <可选项> 连接时使用 LD 脚本
#     flash_program: bin/flash_program.elf # <可选项> 该CPU对应烧写程序，未指定时使用全局烧写程序
#     toolchain_prefix: csky-abiv2-elf     # <可选项> 编译器前缀
## solution component
# hw_info:
#   cpu_id: cpu0
#   board_name: pangu_cpu0
#   cpu_name: CK805EF
#   vendor_name: xuantie
#   chip_name: 'chip_pangu'
#   ld_script: configs/gcc_eflash.ld.S
hw_info:
  cpu_id: ""
  cpu_name: ""
  vendor_name: ""
  chip_name: ""
  ld_script: ""
  flash_program: ""
## 第四部分：编译连接信息
# build_config:                            # <可选项> 编译配置项
#   include:                               # <可选项> 编译时，影响编译器的-I 参数 ,全局有效
#     - src                                #        include 只能是该软件包下的目录，不能使用外部目录
#   internal_include:                      # <可选项> 编译时，影响编译器的-I 参数 ,组件内有效
#     - include
#   cflag: ''                              # <可选项> C 编译器所需要要的编译参数
#   cxxflag: ''                            # <可选项> CXX 编译器所需要要的编译参数
#   asmflag: ''                            # <可选项> 汇编器所需要要参数
#   define:                                # <可选项> 宏定义, 增加编译器的-D 选项,如：
#     XXX: 1                               #   -DXXX=1
#     AAA: 1                               #   -DAAA
#     STR: "abc"                           #   -DSTR="abc"
#   libs:                                  # 该组件中支持的二进制静态库,如：libxxx.a, libyyy.a
#     - xxx                                #   -lxxx
#     - yyy                                #   -lyyy
#   libpath:                               # 指定静态库所在的路径（相对于该组件路径）
#     - libs                               #   -Llibs
build_config:
  cflag: '-Os  -g'
  cxxflag: '-Os  -g'
  include:
    - app/include
  internal_include: ~

  asmflag: ""
  define: ~
  libs:
    - m
  libpath: ~
  ldflag: '-Wl,-zmax-page-size=1024 -Wl,-Map=yoc.map'
#  cflag: '-g -O0 -Wall'
#  cxxflag: '-g -O0 -Wall'
#  asmflag: '-g -O0 -Wall'
# source_file:                             # <可选项> 指定参与编译的源代码文件，支持通配符，采用相对路径
#   - src/*.c                              # 例：组件 src 目录下所有的扩展名为 c 的源代码文件
source_file:
  - app/src/init/cli_cmd.c
  - app/src/init/app_init.c
  - app/src/*.c
## 第五部分：配置信息
# def_config:                              # 组件的可配置项
#   CONFIG_DEBUG: y
#   CONFIG_PARAM_NOT_CHECK: y
#   CONFIG_CLI: y
def_config:
# Board config
  BOARD_BT_SUPPORT: 1

# Kernel Config
  CONFIG_KERNEL_RHINO: 1
  CONFIG_KERNEL_TIMER: 1
  CONFIG_KERNEL_TIMER_MSG_NUM: 40

# KV Confing
  CONFIG_KV_SMART: 1
  CONFIG_KV_ENABLE_CACHE: 1

# BLE HOST Config
  BLE_4_2: 1
  CONFIG_BT_AUTO_DATA_LEN_UPDATE: 1
  CONFIG_BT_CENTRAL: 1
  CONFIG_BT_CONN_TX_MAX: 3
  CONFIG_BT_DEBUG_LOG: 1
  CONFIG_BT_H5_RECV_DATA_LIMIT: 20
  CONFIG_BT_HCI_ACL_FLOW_CONTROL: 1
  CONFIG_BT_HCI_CMD_COUNT: 6
  CONFIG_BT_L2CAP_RX_MTU: 247
  CONFIG_BT_L2CAP_TX_BUF_COUNT: 8
  CONFIG_BT_L2CAP_TX_MTU: 247
  CONFIG_BT_PERIPHERAL: 1
  CONFIG_BT_RX_BUF_COUNT: 4
  CONFIG_BT_RX_BUF_LEN: 512
  CONFIG_BT_SHELL: 1
  CONFIG_BT_SMP: 1
  CONFIG_BT_WHITELIST: 1
  CONFIG_BT_WORK_INDEPENDENCE: 1
  CONFIG_BLE_MESH_PROV: 1
  CONFIG_BT_MESH_APP_KEY_COUNT: 2
  CONFIG_BT_MESH_CFG_CLI: 1
  CONFIG_BT_MESH_CRPL: 128
  CONFIG_BT_MESH_GATT_PROXY: 1
  CONFIG_BT_MESH_HEALTH_CLI: 1
  CONFIG_BT_MESH_MAX_PROV_NODES: 128
  CONFIG_BT_MESH_MAX_STORED_NODES: 128
  CONFIG_BT_MESH_MODEL_GEN_LEVEL_CLI: 1
  CONFIG_BT_MESH_MODEL_GEN_ONOFF_CLI: 1
  CONFIG_BT_MESH_MODEL_GEN_ONOFF_SRV: 1
  CONFIG_BT_MESH_MODEL_GROUP_COUNT: 10
  CONFIG_BT_MESH_MODEL_LIGHT_CTL_CLI: 1
  CONFIG_BT_MESH_MODEL_LIGHT_LIGHTNESS_CLI: 1
  CONFIG_BT_MESH_MODEL_VENDOR_CLI: 1
  CONFIG_BT_MESH_MODEL_VENDOR_SRV: 1
  CONFIG_BT_MESH_PB_GATT: 1
  CONFIG_BT_MESH_PROVISIONER: 1
  CONFIG_BT_MESH_RELAY: 1
  CONFIG_BT_MESH_SUBNET_COUNT: 2
  CONFIG_BT_MESH_USE_SIG_MODEL: 1
  CONFIG_MESH_LPM: 1
  CONFIG_OCC_AUTH: 0
  CONFIG_TSL_DEVICER_MESH: 0

# CLI Config
  CONFIG_CLI: 1

# Debug
  CONFIG_DEBUG: 1
  MESH_DEBUG_RX: 1
  MESH_DEBUG_TX: 1
  CONFIG_APP_VERSION: v1.0.0

## 第六部分：安装信息
# install:
#   - dest: include/                       # 安装的目的路径 dest是相对路径，通常是相对于YoC SDK 安装目录
#     source:                              # 安装源列表
#      - src/*.h                           # 支持通配符，相对路径
## 第七部分：导出部分
# export:
#   - dest: "<SOLUTION_PATH>/generated/data" # 安装的目的路径 dest是相对路径
#     source:                                # 安装源列表
#       - "bootimgs/boot"
#       - "bootimgs/tee"
#       - "bootimgs/mtb"
#       - "configs/config.yaml"