
## 第一部分： 基础信息
name: sdk_chip_cv181xh_bga                          # <必选项> 包名称 （符合C语言变量命名规则），长度少于等于64字节
version: v8.0.0                                    # <必选项> 组件版本号
description: the sdk chip for cv1810x               # <必选项> 建议至少20字以上
type: sdk                                           # <必选项> 组件类型，为：solution, chip, board, common, sdk

## 第二部分：依赖信息
#           指定该组件依赖的组件及版本，版本支持条件比较，支持：>=v1.0, >v1.0, ==v1.0, <=v1.0, <v1.0, v1.0
#           未指定条件时，默认为 ==，如 v1.0 与 ==v1.0
# depends:                                 # <可选项> 该组件依赖其他的组件，合理的依赖才能保证组件能编译、使用
#   - minilibc: v7.2.0
#   - aos: >=v7.2.0
depends:
  - yoc_kernel: v8.0.0
  - libc_stub: v8.0.0
  - posix: v8.0.0
  - vfs: v8.0.0
  - littlefs: v8.0.0
  - lwext4: v8.0.0
  - netmgr: v8.0.0
  - cjson: v8.0.0
  - mpegts: v8.0.0
  - at: v8.0.0
  - cv181xh_huashanpi_evb: v8.0.0
  - chip_cv181x: v8.0.0
  - g711: v8.0.0
  - ntp: v8.0.0
  - drv_wifi_rtl8723ds: v8.0.0
  - drv_bt_rtl8723ds: v8.0.0
  - ble_host: v8.0.0
  - lwip: v8.0.0
  - mbedtls: v8.0.0
  - minialsa: v8.0.0
  - drv_snd_cv181x: v8.0.0
  - drv_sdmmc: v8.0.0
  - fatfs: v8.0.0
  - cvi_mmf_sdk_cv181xx: v8.0.0
  - cvi_platform: v8.0.0
  - cvi_sensor: v8.0.0
  - cherryusb: v8.0.0
  - key_mgr: v8.0.0
  - sec_crypto: v8.0.0
  - bootab: v8.0.0
  - drv_touchscreen_gsl1680: v8.0.0
  - drv_display_st7701s: v8.0.0
  - drv_usbh_class: v8.0.0
  - tiny_bbm: v8.0.0
