
## 第一部分： 基础信息
name: iot_miniapp_daemon                            # <必选项> 包名称 （符合C语言变量命名规则），长度少于等于64字节
version: v8.0.0                                    # <必选项> 组件版本号
description: IoT小程序服务程序，离线ASR               # <必选项> 建议至少20字以上
type: solution                                      # <必选项> 组件类型，为：solution, chip, board, common, sdk

## 第二部分：依赖信息
#           指定该组件依赖的组件及版本，版本支持条件比较，支持：>=v1.0, >v1.0, ==v1.0, <=v1.0, <v1.0, v1.0
#           未指定条件时，默认为 ==，如 v1.0 与 ==v1.0
# depends:                                 # <可选项> 该组件依赖其他的组件，合理的依赖才能保证组件能编译、使用
#   - minilibc: v7.2.0
#   - aos: >=v7.2.0
sdk_chip:
  - sdk_chip_d1: v8.0.0
  - sdk_chip_f133: v8.0.0
  - sdk_chip_cv181xh_bga: v8.0.0

mkflash_script: mkflash.sh

depends:
  - sdk_chip_cv181xh_bga: v8.0.0
  - iot_miniapp_sdk: v8.0.0
  - av: v8.0.0
  - amrnb: v8.0.0
  - amrwb: v8.0.0
  - flac: v8.0.0
  - ogg: v8.0.0
  - opus: v8.0.0
  - pvmp3dec: v8.0.0
  - sonic: v8.0.0
  - speex: v8.0.0
  - speexdsp: v8.0.0
  - netmgr: v8.0.0
  - littlefs: v8.0.0
  - zlib: v8.0.0
  - ntp: v8.0.0
  - smart_audio: v8.0.0
  - drv_amplifier: v8.0.0
  - wifi_provisioning: v8.0.0
  - cjson: v8.0.0
  - alg_pcm_input: v8.0.0
  - alg_record: v8.0.0
  - record: v8.0.0
  - websocket: v8.0.0
  - posto: v8.0.0
  - cxvision: v8.0.0
  - voice_wrapper: v8.0.0
  - httpclient: v8.0.0
  - transport: v8.0.0
  - button: v8.0.0
  - alg_dispatch: v8.0.0         # alg: mind & xuantie
  - alg_kws_mind_v1: v8.0.0 
  - voice_mind: v8.0.0           # alg: mind
  - aui_cloud_mind: v8.0.0
  - adb: v8.0.0
  - clock_alarm: v8.0.0
  - at: v8.0.0
  - ers: v8.0.0
  - ota_module: v8.0.0
  - alg_asr_lyeva: v8.0.0
  - alg_nlu_lyeva: v8.0.0
  - drv_ethernet: v8.0.0
  - fota: v8.0.0

  - ble_mesh: v8.0.0
  - gateway_mgmt: v8.0.0
  - smartliving: v8.0.0
  - tsl_engine: v8.0.0
  - duktape: v8.0.0
  - dut_service: v8.0.0
  - csi2d: v8.0.0
  
## 第三部分：板级信息
# hw_info:                                 # 对 solution、board、chip 三个字段的改进，统称为 hw_info 字段
#   cpu_id: cpu0
#   cpu_name: CK804EF
#   vendor_name: xuantie
#   chip_name: chip_pangu                  # <可选项> 指定芯片组件名,未设置时，使用depends中 chip 第一个组件
#   board_name: pangu_cpu0_evb             # <可选项> 指定开发板组件名，未设置时，使用depends中 board 第一个组件
#   ld_script: configs/gcc_eflash.ld       # <可选项> 连接时使用 LD 脚本，当选把未设置时，使用对应的 board 的 LD 脚本
#   flash_program: bin/flash_program.elf   # <可选项> 芯片全局烧写程序
#   toolchain_prefix: csky-abiv2-elf       # <可选项> 编译器前缀
#   cpu0:
#     cpu_name: CK804EF                    # <必选项> 该芯片使用的 CPU 型号
#     ld_script: configs/gcc_eflash.ld     # <必选项> 连接时使用 LD 脚本
#     flash_program: bin/flash_program.elf # <可选项> 该CPU对应烧写程序，未指定时使用全局烧写程序
#     toolchain_prefix: csky-abiv2-elf     # <可选项> 编译器前缀
#   cpu1:
#     cpu_name: CK804EF                    # <必选项> 该芯片使用的 CPU 型号
#     ld_script: configs/gcc_eflash.ld     # <可选项> 连接时使用 LD 脚本
#     flash_program: bin/flash_program.elf # <可选项> 该CPU对应烧写程序，未指定时使用全局烧写程序
#     toolchain_prefix: csky-abiv2-elf     # <可选项> 编译器前缀
## solution component
# hw_info:
#   cpu_id: cpu0
#   board_name: pangu_cpu0_evb
#   cpu_name: CK805EF
#   vendor_name: xuantie
#   chip_name: 'chip_pangu'
#   ld_script: configs/gcc_eflash.ld.S

## board component
# hw_info:
#   chip_name: chip_pangu
#   ld_script: configs/gcc_eflash.ld

## chip component (单处理器)
# hw_info:
#   cpu_name: CK804EF
#   ld_script: configs/gcc_eflash.ld
#   toolchain_prefix: csky-abiv2-elf
#   flash_program: bin/flash_program.elf

## chip component(多处理器)
# hw_info:
#   cpu0:
#     cpu_name: CK804EF                    # <必选项> 该芯片使用的 CPU 型号
#     ld_script: configs/gcc_eflash.ld     # <必选项> 连接时使用 LD 脚本
#     flash_program: bin/flash_program.elf # <可选项> 该CPU对应烧写程序，未指定时使用全局烧写程序
#     toolchain_prefix: csky-abiv2-elf     # <可选项> 编译器前缀
#   cpu1:
#     cpu_name: CK804EF                    # <必选项> 该芯片使用的 CPU 型号
#     ld_script: configs/gcc_eflash.ld     # <必选项> 连接时使用 LD 脚本
#     flash_program: bin/flash_program.elf # <可选项> 该CPU对应烧写程序，未指定时使用全局烧写程序
#     toolchain_prefix: csky-abiv2-elf     # <可选项> 编译器前缀

hw_info:
  cpu_id: cpu1
  board_name: ""
  #ld_script: configs/gcc_flash_e907_asr.ld

## 第四部分：编译连接信息
# build_config:                            # <可选项> 编译配置项
#   include:                               # <可选项> 编译时，影响编译器的-I 参数 ,全局有效
#     - src                                #        include 只能是该软件包下的目录，不能使用外部目录
#   internal_include:                      # <可选项> 编译时，影响编译器的-I 参数 ,组件内有效
#     - include
#   cflag: ''                              # <可选项> C 编译器所需要要的编译参数
#   cxxflag: ''                            # <可选项> CXX 编译器所需要要的编译参数
#   asmflag: ''                            # <可选项> 汇编器所需要要参数
#   define:                                # <可选项> 宏定义, 增加编译器的-D 选项,如：
#     XXX: 1                               #   -DXXX=1
#     AAA: 1                               #   -DAAA
#     STR: "abc"                           #   -DSTR="abc"
#   libs:                                  # 该组件中支持的二进制静态库,如：libxxx.a, libyyy.a
#     - xxx                                #   -lxxx
#     - yyy                                #   -lyyy
#   libpath:                               # 指定静态库所在的路径（相对于该组件路径）
#     - libs                               #   -Llibs
build_config:
  cflag: -Os
  cxxflag: -Os -fexceptions
  include:
    - app/src
  ldflag: '-Wl,-zmax-page-size=1024 -Wl,-Map=yoc.map'
# source_file:                             # <可选项> 指定参与编译的源代码文件，支持通配符，采用相对路径
#   - src/*.c                              # 例：组件 src 目录下所有的扩展名为 c 的源代码文件
source_file:
  - app/src/*.c
  - app/src/cli/*.c
  - app/src/aui_asr/*.c
  - app/src/player/*.c
  - app/src/voice/*.c
  - app/src/sys/*.c
  - app/src/at_cmd/*.c ? <CONFIG_SMART_SPEAKER_AT>
  - app/src/wifi/*.c
  - app/src/bt/*.c
  - app/src/wifi/multi_ssid/*.c
  - app/src/wifi/wifi_prov/*.c
  - app/src/key_msg/*.c
  - app/src/event_mgr/*.c
  - app/src/display/*.c
  - app/src/display/pwm_led/*.c
  - app/src/factory/*.c
  - app/src/alarms/*.c
  - app/src/button/*.c
  - app/src/miniapp/*.c
  - app/src/linkkit_gateway/*.c
  - app/src/linkkit_gateway/app_gateway_opt/*.c

## 第五部分：配置信息
def_config:                              # 组件的可配置项
    CONFIG_DEBUG: 1
    # CONFIG_DEBUG_MM: 1
    CONFIG_SOFTWDT: 1
    # CONFIG_DEBUG_UTASK: 1
    CONFIG_PTHREAD_DEFAULT_STACK_SIZE: 8192
    CONFIG_SOFTWDT_TASK_STACK_SIZE: 2048
    CLI_CONFIG_STACK_SIZE: 32768
    CLI_TASK_PRIORITY: 5
    CONFIG_USERVICE_EVENT_TASK_STACK_SIZE: 16384
    CONFIG_IPC_RECV_TASK_STACK_SIZE: 4096
    CONFIG_IPC_SERVICE_TASK_STACK_SIZE: 6144
    CONFIG_ARCH_INTERRUPTSTACK: 8192
    CONFIG_SMART_AUDIO_STACK_SIZE: 16384
    CONFIG_SMART_AUDIO_MEDIA_STACK_SIZE: 16384
    ULOG_CONFIG_ASYNC: 1   # ulog异步配置项，1表示开启异步打印，0表示同步打印
    ULOG_CONFIG_SYNC_LOG_DETAILS: 1
    ULOG_CONFIG_DEFAULT_DIR_ASYNC: 1
    ULOG_CONFIG_ASYNC_BUF_SIZE: 81920
    ULOG_CONFIG_LOG_SIZE: 2048
  #  CONFIG_STANDALONE_NVRAM: 1
    CONFIG_FOTA_DATA_IN_RAM: 0
    CONFIG_FOTA_USE_HTTPC: 1
    CONFIG_OTA_GATEWAY_IMG_SIZE: 819200
    CONFIG_HAL_UART_RINGBUF_LEN: 2048
    CONFIG_KERNEL_TIMER_MSG_NUM: 40
    CONFIG_KERNEL_TIMER_STACK_SIZE: 16384
    CONFIG_SMART_SPEAKER_AT: 0
    CONFIG_TOUCH_TASK_STACK_SIZE: 16384
# KV Confing
    CONFIG_KV_SMART: 1
    CONFIG_KV_ENABLE_CACHE: 1
#board config
    CONFIG_BOARD_DISPLAY: 1
    CONFIG_BOARD_VO_OSD: 1
    CONFIG_BOARD_BT: 1
    CONFIG_BOARD_AUDIO: 1
    CONFIG_BOARD_ADC: 1
    CONFIG_BOARD_BUTTON: 1
    CONFIG_BOARD_WIFI: 1
    CONFIG_BOARD_ETH: 0
#av decode
    CONFIG_DECODER_PVMP3: 1
    CONFIG_DECODER_ALAW: 1
    CONFIG_DECODER_AMRNB: 1
    CONFIG_DECODER_AMRWB: 1
    CONFIG_DECODER_OPUS: 1
    CONFIG_DECODER_MULAW: 1
    CONFIG_DECODER_SPEEX: 1
    CONFIG_DECODER_ADPCM_MS: 1
    CONFIG_DECODER_FLAC: 1
#alg config
    CONFIG_ALG_ASR_LYEVA: 1
    CONFIG_POSTO_DEFAULT_TASK_SIZE: 16384
    CONFIG_ALG_ASR_LYEVA_INTENTION: 1  
#UI
    CONFIG_D1_DISP_FORMAT_ARGB8888: 1
# Smartliving Config
    CONFIG_MQTT_RX_MAXLEN: 30720
    OTA_ENABLED: 1
    CONFIG_WIFI_PROV_BLE: 1
    DEVICE_MODEL_GATEWAY: 1
    DM_UNIFIED_SERVICE_POST: 1
    CONFIG_SMARTLIVING_OTA:  1
# Gateway Config
    CONFIG_SDK_VERSION: ble_mesh_gateway_1.0.0
    CONFIG_GATEWAY_SUBDEV_OFFLINE_CHECK: 1
    CONFIG_GW_MAX_DEVICES_META_NUM: 256
    CONFIG_ERS_CONNECTIVITY: 0
# TSL Model Config
    CONFIG_TSL_DEVICER_MESH: 0
    CONFIG_SAVE_JS_TO_RAM: 0
# BLE HOST Config
    CONFIG_BT_HCI_ACL_FLOW_CONTROL: 1
    CONFIG_BT_AUTO_DATA_LEN_UPDATE: 1
# Debug config
    CONFIG_BT_DEBUG_LOG: 1
    MESH_DEBUG_TX: 1
    MESH_DEBUG_RX: 1

## 第六部分：安装信息
# install:
#   - dest: include/                       # 安装的目的路径 dest是相当路径，通常是相对于YoC SDK 安装目录
#     source:                              # 安装源列表
#      - src/*.h                           # 支持通配符，相对路径

## 第七部分：导出部分
# export:
#   - dest: "<SOLUTION_PATH>/generated/data" # 安装的目的路径 dest是相当路径
#     source:                                # 安装源列表
#       - "bootimgs/boot"
#       - "bootimgs/tee"
#       - "bootimgs/mtb"
#       - "configs/config.yaml"
