
## 第一部分： 基础信息
name: xuantie_cpu_sdk                                # <必选项> 包名称 （符合C语言变量命名规则），长度少于等于64字节
version: v8.1.0                                     # <必选项> 组件版本号
description: 面向玄铁处理器的最小cpu sdk             # <必选项> 建议至少20字以上
type: common                                         # <必选项> 组件类型，为：solution, chip, board, common, sdk
tag: 核心模块                                        # <可选项> 组件分类，缺省值： ''
license: Apache license v2.0                         # <可选项> 源代码的许可证，要确保所有代码、文件的许可证不冲突。如：MIT，Apache license v2.0，BSD

## 第二部分：依赖信息
#           指定该组件依赖的组件及版本，版本支持条件比较，支持：>=v1.0, >v1.0, ==v1.0, <=v1.0, <v1.0, v1.0
#           未指定条件时，默认为 ==，如 v1.0 与 ==v1.0
# depends:                                 # <可选项> 该组件依赖其他的组件，合理的依赖才能保证组件能编译、使用
#   - minilibc: v7.2.0
#   - aos: >=v7.2.0
depends:
  # base component
  - yoc_base: v8.1.0
  - libc_bare: v8.1.0
  - libc_stub: v8.1.0
  - libc_freertos: v8.1.0
  - libc_rtthread: v8.1.0
  - semihost2: v8.1.0

  # chip
  - chip_riscv_dummy: v8.1.0

  # boards
  - board_riscv_dummy: v8.1.0

  # chip sdk
  - sdk_chip_riscv_dummy: v8.1.0

  # freertos kernel
  - freertos: v8.1.0

  # rhino kernel
  #- rhino: v8.1.0
  #- rhino_arch: v8.1.0

  # rtt kernel
  - rtthread: v8.1.0

  # demo
  - bare_core_dsp: v8.1.0
  - bare_core_ecc: v8.1.0
  - bare_core_vector: v8.1.0
  - bare_core_matrix: v8.1.0
  - bare_core_lockup: v8.1.0
  - bare_coremark: v8.1.0
  - bare_core_nmi: v8.1.0
  - bare_core_tcm: v8.1.0
  - bare_core_vic: v8.1.0
  - bare_core_wfe: v8.1.0
  - bare_core_wfi: v8.1.0
  - bare_cpp_demo: v8.1.0
  - bare_dhrystone: v8.1.0
  - bare_drv_timer: v8.1.0
  - bare_drv_uart: v8.1.0
  - bare_helloworld: v8.1.0
  - bare_linpack_dp: v8.1.0
  - bare_linpack_sp: v8.1.0
  - bare_whetstone: v8.1.0
  - bare_semihost: v8.1.0
  - bare_semihost2: v8.1.0
  - bare_profiling_perf: v8.1.0
  - mcu_freertos_helloworld: v8.1.0
  - mcu_freertos_cpp: v8.1.0
  - mcu_freertos_kernel: v8.1.0
  - mcu_rtthread_helloworld: v8.1.0
  - mcu_rtthread_cpp: v8.1.0
  - mcu_rtthread_smp: v8.1.0
  - mcu_rtthread_perf: v8.1.0
  - mcu_rtthread_kernel: v8.1.0
  - soc_helloworld: v8.1.0
  - soc_semihost2: v8.1.0
  - soc_smp_demo: v8.1.0
  - soc_core_dsp: v8.1.0
  - soc_core_vector: v8.1.0
  - soc_core_matrix: v8.1.0
  - soc_cpp_demo: v8.1.0
  - soc_kernel_sample: v8.1.0

