
## 第一部分： 基础信息
name: ch2601_evb                                    # <必选项> 包名称 （符合C语言变量命名规则），长度少于等于64字节
version: v7.9.1                                    # <必选项> 组件版本号
description: ch2601 board configure                 # <必选项> 建议至少20字以上
type: board                                         # <必选项> 组件类型，为：solution, chip, board, common, sdk
license: Apache license v2.0                        # <可选项> 源代码的许可证，要确保所有代码、文件的许可证不冲突。如：MIT，Apache license v2.0，BSD

## 第二部分：依赖信息
#           指定该组件依赖的组件及版本
# sdk_chip:                                # <可选项> 该组件依赖sdk组件，合理的依赖才能保证组件能编译、使用
#   - sdk_chip_csky_dummy: v7.4.0
#   - sdk_chip_riscv_dummy: v7.4.0
# depends:                                 # <可选项> 该组件依赖其他的组件，合理的依赖才能保证组件能编译、使用
#   - minilibc: v7.4.0
#   - aos: v7.4.0

## 第三部分：板级信息
# hw_info:                                 # 对 solution、board、chip 三个字段的改进，统称为 hw_info 字段
#   cpu_id: cpu0
#   cpu_name: CK804EF
#   vendor_name: xuantie
#   chip_name: chip_pangu                  # <可选项> 指定芯片组件名,未设置时，使用depends中 chip 第一个组件
#   board_name: pangu_cpu0_evb             # <可选项> 指定开发板组件名，未设置时，使用depends中 board 第一个组件
#   ld_script: configs/gcc_eflash.ld       # <可选项> 连接时使用 LD 脚本，当选把未设置时，使用对应的 board 的 LD 脚本
#   flash_program: bin/flash_program.elf   # <可选项> 芯片全局烧写程序
#   toolchain_prefix: csky-abiv2-elf       # <可选项> 编译器前缀
#   cpu0:
#     cpu_name: CK804EF                    # <必选项> 该芯片使用的 CPU 型号
#     ld_script: configs/gcc_eflash.ld     # <必选项> 连接时使用 LD 脚本
#     flash_program: bin/flash_program.elf # <可选项> 该CPU对应烧写程序，未指定时使用全局烧写程序
#     toolchain_prefix: csky-abiv2-elf     # <可选项> 编译器前缀
#   cpu1:
#     cpu_name: CK804EF                    # <必选项> 该芯片使用的 CPU 型号
#     ld_script: configs/gcc_eflash.ld     # <可选项> 连接时使用 LD 脚本
#     flash_program: bin/flash_program.elf # <可选项> 该CPU对应烧写程序，未指定时使用全局烧写程序
#     toolchain_prefix: csky-abiv2-elf     # <可选项> 编译器前缀

## board component
# hw_info:
#   chip_name: chip_pangu
#   ld_script: configs/gcc_eflash.ld
hw_info:
  vendor_name: xuantie
  chip_name: chip_ch2601
  cpu_name: e906

## 第四部分：编译连接信息
# build_config:                            # <可选项> 编译配置项
#   include:                               # <可选项> 编译时，影响编译器的-I 参数 ,全局有效
#     - src                                #        include 只能是该软件包下的目录，不能使用外部目录
#   internal_include:                      # <可选项> 编译时，影响编译器的-I 参数 ,组件内有效
#     - include
#   cflag: ''                              # <可选项> C 编译器所需要要的编译参数
#   cxxflag: ''                            # <可选项> CXX 编译器所需要要的编译参数
#   asmflag: ''                            # <可选项> 汇编器所需要要参数
#   define:                                # <可选项> 宏定义, 增加编译器的-D 选项,如：
#     XXX: 1                               #   -DXXX=1
#     AAA: 1                               #   -DAAA
#     STR: "abc"                           #   -DSTR="abc"
#   libs:                                  # 该组件中支持的二进制静态库,如：libxxx.a, libyyy.a
#     - xxx                                #   -lxxx
#     - yyy                                #   -lyyy
#   libpath:                               # 指定静态库所在的路径（相对于该组件路径）
#     - libs                               #   -Llibs
build_config:
  cflag: >
    -nostdlib -Wpointer-arith -Wall -Wl,-EL -ffunction-sections -fdata-sections
    -Os -g
  cxxflag: >
    -nostdlib -Wpointer-arith -Wall -Wl,-EL -ffunction-sections -fdata-sections
    -Os -g
  include:
    - include
  prebuild_script: "script/pre_build.sh"
  postbuild_script: "script/aft_build.sh"

# source_file:                             # <可选项> 指定参与编译的源代码文件，支持通配符，采用相对路径
#   - src/*.c                              # 例：组件 src 目录下所有的扩展名为 c 的源代码文件
source_file:
  - "src/*.c"
  - src/audio/*.c ? <CONFIG_BOARD_AUDIO>
  - "src/flash/*.c"
  - "src/uart/*.c"

## 第五部分：配置信息
# def_config:                              # 组件的可配置项
#   CONFIG_DEBUG: y
#   CONFIG_PARAM_NOT_CHECK: y
#   CONFIG_CLI: y
def_config:
  CONFIG_BOARD_CH2601_EVB: 1
  CONFIG_CPU_E906: 1
  CONFIG_XIP: y
  CONFIG_SYSTICK_HZ: 100
  CONFIG_ARCH_INTERRUPTSTACK: 4096
  CONFIG_OTA_AB: 0
  # player
  CONFIG_AEFXER_IPC: 0
  CONFIG_AEFXER_SONA: 0
  CONFIG_ATEMPOER_IPC: 0
  CONFIG_ATEMPOER_SONIC: 1
  CONFIG_AVPARSER_ADTS: 0
  CONFIG_AVPARSER_MP3: 1
  CONFIG_DECODER_ADPCM_MS: 0
  CONFIG_DECODER_ALAW: 0
  CONFIG_DECODER_AMRNB: 0
  CONFIG_DECODER_AMRWB: 0
  CONFIG_DECODER_FLAC: 0
  CONFIG_DECODER_IPC: 0
  CONFIG_DECODER_MULAW: 0
  CONFIG_DECODER_OPUS: 0
  CONFIG_DECODER_PCM: 1
  CONFIG_DECODER_PVMP3: 1
  CONFIG_DECODER_SPEEX: 0
  CONFIG_DEMUXER_ADTS: 0
  CONFIG_DEMUXER_AMR: 0
  CONFIG_DEMUXER_ASF: 0
  CONFIG_DEMUXER_FLAC: 0
  CONFIG_DEMUXER_MP3: 1
  CONFIG_DEMUXER_MP4: 0
  CONFIG_DEMUXER_OGG: 0
  CONFIG_DEMUXER_RAWAUDIO: 0
  CONFIG_DEMUXER_TS: 0
  CONFIG_DEMUXER_WAV: 0
  CONFIG_EQXER_IPC: 0
  CONFIG_EQXER_SILAN: 0
  CONFIG_FFTXER_IPC: 0
  CONFIG_FFTXER_SPEEX: 0
  CONFIG_RESAMPLER_IPC: 0
  CONFIG_RESAMPLER_SPEEX: 1
  CONFIG_STREAMER_CRYPTO: 0
  CONFIG_STREAMER_FIFO: 0
  CONFIG_STREAMER_FILE: 1
  CONFIG_STREAMER_HLS: 0
  CONFIG_STREAMER_HTTP: 0
  CONFIG_STREAMER_MEM: 1
  CONFIG_PLAYER_TASK_STACK_SIZE: 2048
  CONFIG_AV_STREAM_INNER_BUF_SIZE: 256
  CONFIG_AV_PROBE_SIZE_MAX: 1024                # for av foramt probe
  CONFIG_AV_AO_CHANNEL_NUM: 1                   # mono output
  CONFIG_AV_SAMPLE_NUM_PER_FRAME_MAX: 80
  HAVE_MBEDTLS_USER_CONFIG: 1
  CONFIG_USING_TLS: 1
  CONFIG_SEC_CRYPTO_SHA_SW: 1
  CONFIG_FOTA_BUFFER_SIZE: 512
  CLI_CONFIG_STACK_SIZE: 4096
  # filesystem
  CONFIG_FS_LFS: y

## 第六部分：安装信息
# install:
#   - dest: include/                       # 安装的目的路径 dest是相对路径，通常是相对于YoC SDK 安装目录
#     source:                              # 安装源列表
#      - src/*.h                           # 支持通配符，相对路径

## 第七部分：导出部分
# export:
#   - dest: "<SOLUTION_PATH>/generated/data" # 安装的目的路径 dest是相对路径
#     source:                                # 安装源列表
#       - "bootimgs/boot"
#       - "bootimgs/tee"
#       - "bootimgs/mtb"
#       - "configs/config.yaml"
