
## 第一部分： 基础信息
name: bl606p_evb_e907                               # <必选项> 包名称 （符合C语言变量命名规则），长度少于等于64字节
version: v7.9.1                                   # <必选项> 组件版本号
description: bl606 board configure                  # <必选项> 建议至少20字以上
type: board                                         # <必选项> 组件类型，为：solution, chip, board, common, sdk
license: Apache license v2.0                        # <可选项> 源代码的许可证，要确保所有代码、文件的许可证不冲突。如：MIT，Apache license v2.0，BSD

## 第二部分：依赖信息
#           指定该组件依赖的组件及版本
# sdk_chip:                                # <可选项> 该组件依赖sdk组件，合理的依赖才能保证组件能编译、使用
#   - sdk_chip_csky_dummy: v7.4.0
#   - sdk_chip_riscv_dummy: v7.4.0
# depends:                                 # <可选项> 该组件依赖其他的组件，合理的依赖才能保证组件能编译、使用
#   - minilibc: v7.4.0
#   - aos: v7.4.0

## 第三部分：板级信息
# hw_info:                                 # 对 solution、board、chip 三个字段的改进，统称为 hw_info 字段
#   cpu_id: cpu0
#   cpu_name: CK804EF
#   vendor_name: xuantie
#   chip_name: chip_pangu                  # <可选项> 指定芯片组件名,未设置时，使用depends中 chip 第一个组件
#   board_name: pangu_cpu0_evb             # <可选项> 指定开发板组件名，未设置时，使用depends中 board 第一个组件
#   ld_script: configs/gcc_eflash.ld       # <可选项> 连接时使用 LD 脚本，当选把未设置时，使用对应的 board 的 LD 脚本
#   flash_program: bin/flash_program.elf   # <可选项> 芯片全局烧写程序
#   toolchain_prefix: csky-abiv2-elf       # <可选项> 编译器前缀
#   cpu0:
#     cpu_name: CK804EF                    # <必选项> 该芯片使用的 CPU 型号
#     ld_script: configs/gcc_eflash.ld     # <必选项> 连接时使用 LD 脚本
#     flash_program: bin/flash_program.elf # <可选项> 该CPU对应烧写程序，未指定时使用全局烧写程序
#     toolchain_prefix: csky-abiv2-elf     # <可选项> 编译器前缀
#   cpu1:
#     cpu_name: CK804EF                    # <必选项> 该芯片使用的 CPU 型号
#     ld_script: configs/gcc_eflash.ld     # <可选项> 连接时使用 LD 脚本
#     flash_program: bin/flash_program.elf # <可选项> 该CPU对应烧写程序，未指定时使用全局烧写程序
#     toolchain_prefix: csky-abiv2-elf     # <可选项> 编译器前缀

## board component
# hw_info:
#   chip_name: chip_pangu
#   ld_script: configs/gcc_eflash.ld
hw_info:
  cpu_id: cpu1
  chip_name: chip_bl606p

## 第四部分：编译连接信息
# build_config:                            # <可选项> 编译配置项
#   include:                               # <可选项> 编译时，影响编译器的-I 参数 ,全局有效
#     - src                                #        include 只能是该软件包下的目录，不能使用外部目录
#   internal_include:                      # <可选项> 编译时，影响编译器的-I 参数 ,组件内有效
#     - include
#   cflag: ''                              # <可选项> C 编译器所需要要的编译参数
#   cxxflag: ''                            # <可选项> CXX 编译器所需要要的编译参数
#   asmflag: ''                            # <可选项> 汇编器所需要要参数
#   define:                                # <可选项> 宏定义, 增加编译器的-D 选项,如：
#     XXX: 1                               #   -DXXX=1
#     AAA: 1                               #   -DAAA
#     STR: "abc"                           #   -DSTR="abc"
#   libs:                                  # 该组件中支持的二进制静态库,如：libxxx.a, libyyy.a
#     - xxx                                #   -lxxx
#     - yyy                                #   -lyyy
#   libpath:                               # 指定静态库所在的路径（相对于该组件路径）
#     - libs                               #   -Llibs
build_config:
  cflag: >
        -c -g -Os -ffunction-sections -fdata-sections -Wall -fno-common 
        -Os -gdwarf -ffunction-sections -fdata-sections -fstrict-volatile-bitfields -fshort-enums 
        -fno-strict-aliasing -fno-omit-frame-pointer
        -Wall -Wno-error=unused-function -Wno-error=unused-but-set-variable -Wno-error=unused-variable 
        -Wno-error=deprecated-declarations -Wno-unused-parameter -Wno-sign-compare 
        -Wno-old-style-declaration -mabi=ilp32f -mtune=e907 -mcmodel=medany 

  asmflag: -c -g -ffunction-sections -fdata-sections -Wall
  ldflag: -Wl,-Map=yoc.map
  cxxflag: >
        -D_GLIBCXX_HAS_GTHREADS
        -std=gnu++11 -fno-common -fno-exceptions -ffunction-sections -fdata-sections -fomit-frame-pointer -fpermissive -g -Os
  include:
    - include
    - src
  libs:
    - m
  prebuild_script: "script/pre_build.sh"
  postbuild_script: "script/aft_build.sh"

# source_file:                             # <可选项> 指定参与编译的源代码文件，支持通配符，采用相对路径
#   - src/*.c                              # 例：组件 src 目录下所有的扩展名为 c 的源代码文件
source_file:
  - "src/*.c"
  - "src/audio/*.c ? <CONFIG_BOARD_AUDIO>"
  - "src/button/*.c"
  - "src/adc/*.c"
  - "src/bt/*.c"
  - "src/gpio/*.c"
  - "src/led/*.c"
  - "src/pwm/*.c"
  - "src/uart/*.c"
  - "src/spi/*.c"
  - "src/wifi/*.c"
  - "src/amp/*.c"
  - "src/vendor/*.c"
  - "src/flash/*.c"

## 第五部分：配置信息
# def_config:                              # 组件的可配置项
#   CONFIG_DEBUG: y
#   CONFIG_PARAM_NOT_CHECK: y
#   CONFIG_CLI: y
def_config:
  CONFIG_BOARD_BL606P_EVB: 1
  CONFIG_ENABLE_BOTTOM_PA: 0
  CONFIG_DISABLE_PA_DAC: 0
  WITH_LWIP: 1
  CONFIG_SYSTICK_HZ: 1000
  #CONFIG_KERNEL_WORKQUEUE: 1
  # CONFIG_INIT_TASK_STACK_SIZE: 4096
  CLI_CONFIG_STACK_SIZE: 8192
  CONFIG_LFS_BLOCK_CYCLES: 500
  CONFIG_LFS_MOUNTPOINT: "/"
  CONFIG_CPU_E907FP: 1
  CONFIG_HAL_UART_FIFO_SIZE: 32
  HAVE_MBEDTLS_USER_CONFIG: 1
  CONFIG_KV_SMART: 1
  POSIX_DEVICE_IO_NEED: 1
  CONFIG_USING_TLS: y
  CPU_M1: 1
  CPU_ID: "M0"
  CPU_M0: y
  ARCH_RISCV: y
  WLAN_DEBUG: y
  BFLB_USE_HAL_DRIVER: y
  CONF_ENABLE_FRAME_PTR: y
  CONF_USER_ENABLE_PSRAM: y
  CONFIG_CHIP_BL606P_E907: 1
  # CONFIG_XIP: y
  CONFIG_SOFTWDT: y
  CONFIG_SOFTWDT_TASK_STACK_SIZE: 2048
  CONFIG_MAX_PARTITION_NUM: 16
  #sec_crypto
  CONFIG_SEC_CRYPTO_ECC_SW: 1
  CONFIG_SEC_CRYPTO_AES_SW: 1
  CONFIG_SEC_CRYPTO_SHA_SW: 1
  CONFIG_SEC_CRYPTO_RSA_SW: 1
  CONFIG_SEC_CRYPTO_RNG_SW: 1
  CONFIG_PARITION_NO_VERIFY: 0
  CONFIG_FOTA_IMG_AUTHENTICITY_NOT_CHECK: 0
  CONFIG_TB_KP: 1
  CONFIG_KP_BUFFER_LEN: 4096
  CONFIG_KEY_MGR_KP_PROTECT: 1
  #app define
  CONFIG_BT_BREDR: 1
  CONFIG_BT_SMP: 1
  CONFIG_BT_A2DP: 1
  CONFIG_BT_AVRCP: 1
  CONFIG_BT_HFP_HF: 1
  CONFIG_BT_HFP: 0
  # player
  CONFIG_AV_AO_CHANNEL_NUM: 1
  CONFIG_AEFXER_SONA: 0
  CONFIG_RESAMPLE_RATE: 48000
  # fota
  CONFIG_FOTA_BUFFER_SIZE: 16384
  # filesystem
  CONFIG_FS_LFS: y

## 第六部分：安装信息
# install:
#   - dest: include/                       # 安装的目的路径 dest是相对路径，通常是相对于YoC SDK 安装目录
#     source:                              # 安装源列表
#      - src/*.h                           # 支持通配符，相对路径

## 第七部分：导出部分
# export:
#   - dest: "<SOLUTION_PATH>/generated/data" # 安装的目的路径 dest是相对路径
#     source:                                # 安装源列表
#       - "bootimgs/boot"
#       - "bootimgs/tee"
#       - "bootimgs/mtb"
#       - "configs/config.yaml"

