
## 第一部分： 基础信息
name: sdk_longyuan                                        # <必选项> 包名称 （符合C语言变量命名规则），长度少于等于64字节
version: v7.9.1                                    # <必选项> 组件版本号
description: the sdk for longyuan                  # <必选项> 建议至少20字以上
type: common                                        # <必选项> 组件类型，为：solution, chip, board, common, sdk

## 第二部分：依赖信息
#           指定该组件依赖的组件及版本，版本支持条件比较，支持：>=v1.0, >v1.0, ==v1.0, <=v1.0, <v1.0, v1.0
#           未指定条件时，默认为 ==，如 v1.0 与 ==v1.0
# depends:                                 # <可选项> 该组件依赖其他的组件，合理的依赖才能保证组件能编译、使用
#   - minilibc: v7.2.0
#   - aos: >=v7.2.0
depends:
  - adb: v7.9.1
  - aos: v7.9.1
  - bootab: v7.9.1
  - button: v7.9.1
  - cli: v7.9.1
  - csi: v7.9.1
  - debug: v7.9.1
  - ers: v7.9.1
  - fota: v7.9.1
  - ipc: v7.9.1
  - key_mgr: v7.9.1
  - kv: v7.9.1
  - libc_stub: v7.9.1
  - log_ipc: v7.9.1
  - minialsa: v7.9.1
  - minilibc: v7.9.1
  - netmgr: v7.9.1
  - ntp: v7.9.1
  - partition: v7.9.1
  - posix: v7.9.1
  - rhino: v7.9.1
  - rhino_arch: v7.9.1
  - rhino_pwrmgmt: v7.9.1
  - sec_crypto: v7.9.1
  - transport: v7.9.1
  - ulog: v7.9.1
  - uservice: v7.9.1
  - vfs: v7.9.1
  - wifi_provisioning: v7.9.1
  - at: v7.9.1
  - device: v7.9.1

# 3rd
  - zlib: v7.9.1
  - websocket: v7.9.1
  - httpclient: v7.9.1
  - lwip: v7.9.1
  - mbedtls: v7.9.1
  - littlefs: v7.9.1
  - cjson: v7.9.1
  - sntp: v7.9.1
  - breeze: v7.9.1
  - duktape: v7.9.1
  - smartliving: v7.9.1

# UI core
  - lvgl: v7.9.1
  - iot_miniapp_sdk: v7.9.1

# Voice
  - cxvision: v7.9.1
  - posto: v7.9.1
  - voice_wrapper: v7.9.1
  - voice_mind: v7.9.1
  - alg_kws_mind: v7.9.1
  - alg_kws_mind_v1: v7.9.1
  - voice_lyeva: v7.9.1
  - alg_kws_lyeva: v7.9.1
  - alg_dispatch: v7.9.1
  - alg_record: v7.9.1
  - alg_pcm_input: v7.9.1
  - aui_cloud_mind: v7.9.1
  - record: v7.9.1
  - clock_alarm: v7.9.1
  - alg_asr_lyeva: v7.9.1
  - alg_nlu_lyeva: v7.9.1
  - us_cloud: v7.9.1
  - us_algo_c906: v7.9.1

# Connectivity
  - ble_host: v7.9.1
  - ble_mesh: v7.9.1
  - dut_service: v7.9.1
  - gateway_mgmt: v7.9.1
  - tsl_engine: v7.9.1
  - ota_module: v7.9.1

# Media base
  - smart_audio: v7.9.1
  - pvmp3dec: v7.9.1
  - speexdsp: v7.9.1
  - sonic: v7.9.1

# Media pro
  - av: v7.9.1
  - amrnb: v7.9.1
  - amrwb: v7.9.1
  - flac: v7.9.1
  - ogg: v7.9.1
  - opus: v7.9.1
  - speex: v7.9.1

# Driver
  - drv_wifi_rtl8723ds: v7.9.1
  - drv_bt_rtl8723ds: v7.9.1
  - drv_amplifier: v7.9.1
  - drv_light: v7.9.1

# BL606P
  - chip_bl606p: v7.9.1
  - bl606p_evb_e907: v7.9.1
  - bl606p_evb_c906: v7.9.1
  - bl606p_boot: v7.9.1
  - drv_snd_bl606p: v7.9.1
  - bl606p_bthost: v7.9.1
  - bl606p_btprofile: v7.9.1
  - bl606p_wifimgmr: v7.9.1
  - bl606p_blimpls: v7.9.1
  - bl606p_btcontroller: v7.9.1
  - bl606p_firmware: v7.9.1
  - bl606p_phyrf: v7.9.1
  - bl606p_player: v7.9.1
  - drv_wifi_bl606p: v7.9.1

# D1 & F133
  - chip_d1: v7.9.1
  - d1_dockpro_evb: v7.9.1
  - f133_evb: v7.9.1
  - d1_boot_demo: v7.9.1

# CV181X
  - chip_cv181x: v7.9.1
  - cv181xh_huashanpi_evb: v7.9.1
  - cv181xh_boot: v7.9.1

# SDK
  - yoc_kernel: v7.9.1
  - sdk_chip_bl606p_e907: v7.9.1
  - sdk_chip_d1: v7.9.1
  - sdk_chip_f133: v7.9.1

# BLE Demos
  - ble_advertising_demo: v7.9.1
  - ble_bas_demo: v7.9.1
  - ble_dis_demo: v7.9.1
  - ble_hid_keyboard_demo: v7.9.1
  - ble_hrs_demo: v7.9.1
  - ble_ibeacon_demo: v7.9.1
  - ble_ibeacon_apple_demo: v7.9.1
  - ble_scanner_demo: v7.9.1
  - ble_shell_demo: v7.9.1
  - ble_uart_profile_client_demo: v7.9.1
  - ble_uart_profile_server_demo: v7.9.1

# BLE MESH Demos
  - mesh_provisioner_demo: v7.9.1
  - mesh_light_node_demo: v7.9.1
  - mesh_shell: v7.9.1
  - mesh_switch_node_demo: v7.9.1

# HAL Demos
  - hal_uart_demo: v7.9.1
  - display_drv_demo: v7.9.1

# Solution
  - ble_mesh_gateway_demo: v7.9.1
  - smart_speaker_v2: v7.9.1
  - smart_panel_lvgl: v7.9.1
  - smart_panel_miniapp: v7.9.1
  - smart_speaker_alg_bl606p_lyeva: v7.9.1

# Sub Module Demo
  - fota_demo: v7.9.1
  - wifi_ble_provisioning_demo: v7.9.1
  - bt_audio_demo: v7.9.1
  - gprs_demo: v7.9.1

# UI demo
  - iot_miniapp_daemon: v7.9.1
  - iot_miniapp_benchmark: v7.9.1
  - iot_miniapp_ui_demo: v7.9.1
  - iot_miniapp_jsapi_demo: v7.9.1
  - iot_miniapp_sdk: v7.9.1
  - lvgl_demo: v7.9.1
