
## 第一部分： 基础信息
name: sdk_longyuan                                        # <必选项> 包名称 （符合C语言变量命名规则），长度少于等于64字节
version: v8.0.0                                    # <必选项> 组件版本号
description: the sdk for longyuan                  # <必选项> 建议至少20字以上
type: common                                        # <必选项> 组件类型，为：solution, chip, board, common, sdk

## 第二部分：依赖信息
#           指定该组件依赖的组件及版本，版本支持条件比较，支持：>=v1.0, >v1.0, ==v1.0, <=v1.0, <v1.0, v1.0
#           未指定条件时，默认为 ==，如 v1.0 与 ==v1.0
# depends:                                 # <可选项> 该组件依赖其他的组件，合理的依赖才能保证组件能编译、使用
#   - minilibc: v7.2.0
#   - aos: >=v7.2.0
depends:
  - adb: v8.0.0
  - aos: v8.0.0
  - bootab: v8.0.0
  - button: v8.0.0
  - cli: v8.0.0
  - csi: v8.0.0
  - debug: v8.0.0
  - ers: v8.0.0
  - fota: v8.0.0
  - ipc: v8.0.0
  - key_mgr: v8.0.0
  - kv: v8.0.0
  - libc_stub: v8.0.0
  - log_ipc: v8.0.0
  - minialsa: v8.0.0
  - minilibc: v8.0.0
  - netmgr: v8.0.0
  - ntp: v8.0.0
  - partition: v8.0.0
  - posix: v8.0.0
  - rhino: v8.0.0
  - rhino_arch: v8.0.0
  - rhino_pwrmgmt: v8.0.0
  - sec_crypto: v8.0.0
  - transport: v8.0.0
  - ulog: v8.0.0
  - uservice: v8.0.0
  - vfs: v8.0.0
  - wifi_provisioning: v8.0.0
  - at: v8.0.0
  - device: v8.0.0

# 3rd
  - zlib: v8.0.0
  - websocket: v8.0.0
  - httpclient: v8.0.0
  - lwip: v8.0.0
  - mbedtls: v8.0.0
  - littlefs: v8.0.0
  - cjson: v8.0.0
  - sntp: v8.0.0
  - breeze: v8.0.0
  - duktape: v8.0.0
  - smartliving: v8.0.0

# UI core
  - lvgl: v8.0.0
  - iot_miniapp_sdk: v8.0.0

# Voice
  - cxvision: v8.0.0
  - posto: v8.0.0
  - voice_wrapper: v8.0.0
  - voice_mind: v8.0.0
  - alg_kws_mind: v8.0.0
  - alg_kws_mind_v1: v8.0.0
  - voice_lyeva: v8.0.0
  - alg_kws_lyeva: v8.0.0
  - alg_dispatch: v8.0.0
  - alg_record: v8.0.0
  - alg_pcm_input: v8.0.0
  - aui_cloud_mind: v8.0.0
  - record: v8.0.0
  - clock_alarm: v8.0.0
  - alg_asr_lyeva: v8.0.0
  - alg_nlu_lyeva: v8.0.0
  - us_cloud: v8.0.0
  - us_algo_c906: v8.0.0

# Connectivity
  - ble_host: v8.0.0
  - ble_mesh: v8.0.0
  - dut_service: v8.0.0
  - gateway_mgmt: v8.0.0
  - tsl_engine: v8.0.0
  - ota_module: v8.0.0

# Media base
  - smart_audio: v8.0.0
  - pvmp3dec: v8.0.0
  - speexdsp: v8.0.0
  - sonic: v8.0.0

# Media pro
  - av: v8.0.0
  - amrnb: v8.0.0
  - amrwb: v8.0.0
  - flac: v8.0.0
  - ogg: v8.0.0
  - opus: v8.0.0
  - speex: v8.0.0

# Driver
  - drv_wifi_rtl8723ds: v8.0.0
  - drv_bt_rtl8723ds: v8.0.0
  - drv_amplifier: v8.0.0
  - drv_light: v8.0.0

# BL606P
  - chip_bl606p: v8.0.0
  - bl606p_evb_e907: v8.0.0
  - bl606p_evb_c906: v8.0.0
  - bl606p_boot: v8.0.0
  - drv_snd_bl606p: v8.0.0
  - bl606p_bthost: v8.0.0
  - bl606p_btprofile: v8.0.0
  - bl606p_wifimgmr: v8.0.0
  - bl606p_blimpls: v8.0.0
  - bl606p_btcontroller: v8.0.0
  - bl606p_firmware: v8.0.0
  - bl606p_phyrf: v8.0.0
  - bl606p_player: v8.0.0
  - drv_wifi_bl606p: v8.0.0

# D1 & F133
  - chip_d1: v8.0.0
  - d1_dockpro_evb: v8.0.0
  - f133_evb: v8.0.0
  - d1_boot_demo: v8.0.0

# CV181X
  - chip_cv181x: v8.0.0
  - cv181xh_huashanpi_evb: v8.0.0
  - cv181xh_boot: v8.0.0

# SDK
  - yoc_kernel: v8.0.0
  - sdk_chip_bl606p_e907: v8.0.0
  - sdk_chip_d1: v8.0.0
  - sdk_chip_f133: v8.0.0

# BLE Demos
  - ble_advertising_demo: v8.0.0
  - ble_bas_demo: v8.0.0
  - ble_dis_demo: v8.0.0
  - ble_hid_keyboard_demo: v8.0.0
  - ble_hrs_demo: v8.0.0
  - ble_ibeacon_demo: v8.0.0
  - ble_ibeacon_apple_demo: v8.0.0
  - ble_scanner_demo: v8.0.0
  - ble_shell_demo: v8.0.0
  - ble_uart_profile_client_demo: v8.0.0
  - ble_uart_profile_server_demo: v8.0.0

# BLE MESH Demos
  - mesh_provisioner_demo: v8.0.0
  - mesh_light_node_demo: v8.0.0
  - mesh_shell: v8.0.0
  - mesh_switch_node_demo: v8.0.0

# HAL Demos
  - hal_uart_demo: v8.0.0
  - display_drv_demo: v8.0.0

# Solution
  - ble_mesh_gateway_demo: v8.0.0
  - smart_speaker_v2: v8.0.0
  - smart_panel_lvgl: v8.0.0
  - smart_panel_miniapp: v8.0.0
  - smart_speaker_alg_bl606p_lyeva: v8.0.0

# Sub Module Demo
  - fota_demo: v8.0.0
  - wifi_ble_provisioning_demo: v8.0.0
  - bt_audio_demo: v8.0.0
  - gprs_demo: v8.0.0

# UI demo
  - iot_miniapp_daemon: v8.0.0
  - iot_miniapp_benchmark: v8.0.0
  - iot_miniapp_ui_demo: v8.0.0
  - iot_miniapp_jsapi_demo: v8.0.0
  - iot_miniapp_sdk: v8.0.0
  - lvgl_demo: v8.0.0
