
## 第一部分： 基础信息
name: sdk_chip_bl606p_e907                           # <必选项> 包名称 （符合C语言变量命名规则），长度少于等于64字节
version: v8.0.0                                     # <必选项> 组件版本号
description: chip sdk for bl606p e907                # <必选项> 建议至少20字以上
type: sdk                                            # <必选项> 组件类型，为：solution, chip, board, common, sdk

tag: 核心模块                                         # <可选项> 组件分类，缺省值： ''
license: Apache license v2.0                         # <可选项> 源代码的许可证，要确保所有代码、文件的许可证不冲突。如：MIT，Apache license v2.0，BSD

## 第二部分：依赖信息
#           指定该组件依赖的组件及版本，版本支持条件比较，支持：>=v1.0, >v1.0, ==v1.0, <=v1.0, <v1.0, v1.0
#           未指定条件时，默认为 ==，如 v1.0 与 ==v1.0
# depends:                                 # <可选项> 该组件依赖其他的组件，合理的依赖才能保证组件能编译、使用
#   - minilibc: v7.2.0
#   - aos: >=v7.2.0
depends:
  - yoc_base: v8.0.0
  - rhino: v8.0.0
  - rhino_arch: v8.0.0
  - rhino_pwrmgmt: v8.0.0
  # - freertos: v8.0.0
  # - rtthread: v8.0.0
  - bl606p_evb_e907: v8.0.0
  - chip_bl606p: v8.0.0
  - libc_stub: v8.0.0
  - posix: v8.0.0
  - vfs: v8.0.0
  - minialsa: v8.0.0
  - drv_snd_bl606p: v8.0.0
  - drv_wifi_bl606p: v8.0.0
  - bl606p_wifimgmr: v8.0.0
  - bl606p_firmware: v8.0.0
  - bl606p_phyrf: v8.0.0
  - bl606p_bthost: v8.0.0
  - bl606p_blimpls: v8.0.0
  - bl606p_btprofile: v8.0.0
  - bl606p_btcontroller: v8.0.0
  - bl606p_player: v8.0.0
  - lwip: v8.0.0
  - mbedtls: v8.0.0
  - ipc: v8.0.0
  - log_ipc: v8.0.0
  - bootab: v8.0.0
  - key_mgr: v8.0.0
  - sec_crypto: v8.0.0
 