hw_info:
  board_name: mit_v2
  ld_script: gcc_flash.ld
type: solution
name: smart_speaker_demo
description: 智能音箱例程
keywords:
  - sc5654
author: feimi
license: Apache license v2.0
depends:
  - aos: v7.4.3
  - rhino: v7.4.3
  - aui_aliyunnls: v7.4.3
  - av: v7.4.3
  - flac: v7.4.3
  - amrnb: v7.4.3
  - amrwb: v7.4.3
  - pvmp3dec: v7.4.3
  - speexdsp: v7.4.3
  - mit_v2: v7.4.3
  - chip_sc5654: v7.4.3
  - cjson: v7.4.3
  - clock_alarm: v7.4.3
  - console: v7.4.3
  - csi: v7.4.3
  - drivers: v7.4.3
  - drv_sdmmc: v7.4.3
  - drv_snd_sc5654: v7.4.3
  - drv_wifi_rtl8723ds: v7.4.3
  - drv_leds: v7.4.3
  - fatfs: v7.4.3
  - fota: v7.4.3
  - ipc: v7.4.3
  - kv: v7.4.3
  - lwip: v7.4.3
  - ntp: v7.4.3
  - mbedtls: v7.4.3
  - mic: v7.4.3
  - minialsa: v7.4.3
  - minilibc: v7.4.3
  - netmgr: v7.4.3
  - posix: v7.4.3
  - record: v7.4.3
  - vfs: v7.4.3
  - voice: v7.4.3
  - webclient: v7.4.3
  - websocket: v7.4.3
  - adc_button: v7.4.3
  - wifi_provisioning: v7.4.3
  - smartliving: v7.4.3
  - fct: v7.4.3
  - httpclient: v7.4.3
  - transport: v7.4.3
  - yoc_sc5654: v7.4.3
  - littlefs: v7.4.3
def_config:
  CONFIG_ARCH_INTERRUPTSTACK: 4096
  CONFIG_CLI: 1
  CONFIG_CPU: ck803ef
  CONFIG_CPU_CK803EF: 1
  CONFIG_DEBUG: 1
  CONFIG_KERNEL_TIMER_MSG_NUM: 30
  CONFIG_KERNEL_TIMER_STACK_SIZE: 2048
  CONFIG_KV_SMART: 1
  CONFIG_NON_ADDRESS_FLASH: 1
  CONFIG_PARAM_NOT_CHECK: 1
  CONFIG_SOFTWDT: 1
  CONFIG_SYSTICK_HZ: 100
  CONFIG_TCPIP: 1
  CONFIG_USING_TLS: 1
  CONFIG_VENDOR_NAME: silan
  CONFIG_RESAMPLER_SILAN: 1
  CONFIG_RESAMPLER_SPEEX: 0
  CONFIG_RESAMPLER_IPC: 0
  CONFIG_AEFXER_SONA: 0
  CONFIG_AEFXER_IPC: 0
  CONFIG_DECODER_PCM: 1
  CONFIG_DECODER_PVMP3: 1
  CONFIG_DECODER_FLAC: 0
  CONFIG_DECODER_ADPCM_MS: 0
  CONFIG_DECODER_AMRNB: 0
  CONFIG_DECODER_AMRWB: 0
  CONFIG_DECODER_IPC: 0
build_config:
  internal_include:
    - ""
  include:
    - app/include
    - app/src
    - app/src/audio
    - app/src/aui_cloud
    - app/src/wifi_prov_ack
    - app/src/led
  cflag: -Os  -g  -Wall  -ffunction-sections -fdata-sections -mhard-float  -Wl,-zmax-page-size=1024 -Wno-address -Wno-unused-but-set-variable -Wno-main -Wno-unused-function
  cxxflag: -Os  -g  -Wall  -ffunction-sections -fdata-sections -mhard-float  -Wl,-zmax-page-size=1024 -Wno-address -Wno-unused-but-set-variable -Wno-main -Wno-unused-function
  asmflag: ""
  ldflag: -Wl,-zmax-page-size=1024 -mhard-float -Wl,-ckmap="yoc.map"
  define:
    - ""
  libs:
    - m
    - resample
  libpath: ~
source_file:
  - app/src/*.c
  - app/src/audio/*.c
  - app/src/vad/*.c
  - app/src/aui_cloud/aliyunnls/*.c
  - app/src/wifi_prov_ack/*.c
  - app/src/led/*.c
  - app/src/voice_debug/t-head/*.c ? <CONFIG_THEAD_DSP>
  - app/src/voice_debug/mit/*.c ? <CONFIG_MIT_DSP>
  - app/src/voice_debug/huwen/*.c ? <CONFIG_HUWEN_DSP>
  - app/src/fct/mit/*.c ? <BOARD_MIT_V2>
  - app/src/fct/org/*.c ? <BOARD_CB5654>
link_config:
  path: ~
  library: ~
hidden: false
homepage: https://www.xrvm.cn
