name: d1_boot_demo
version: v8.0.0                                     # <必选项> 组件版本号
description: BootLoader for D1

type: solution

hw_info:
  cpu_id: cpu0
  chip_name: chip_d1
  ld_script: gcc_flash.ld

depends:                                       # 该组件依赖其他的组件
  - csi: v8.0.0
  - chip_d1: v8.0.0
  - boot: v8.0.0
  - partition: v8.0.0
  - sec_crypto: v8.0.0
  - key_mgr: v8.0.0
  - xz: v8.0.0

# 编译参数
build_config:
  include:
    - app/include
    - board/include
  libpath: ""
  cflag: >
        -c -g -Os -ffunction-sections -fdata-sections -Wall -fno-common -fno-asynchronous-unwind-tables
  asmflag: -c -g -ffunction-sections -fdata-sections -Wall
  cxxflag: >
        -D_GLIBCXX_HAS_GTHREADS
        -std=gnu++11 -fno-common -fno-exceptions -ffunction-sections -fdata-sections -fomit-frame-pointer -fpermissive -g -Os
        -fno-asynchronous-unwind-tables
  ldflag: -Wl,--gc-sections -lstdc++ -lsupc++ -lm -lc -lgcc -lnosys -nostartfiles --specs=nosys.specs -fno-asynchronous-unwind-tables -Wl,-zmax-page-size=1024 -Wl,-Map=boot.map


# 源文件
source_file:
  - app/src/*.c
  - porting/*.c
  - board/src/*.c

def_config:
  CONFIG_DEBUG: 3
  # CONFIG_MM_DETECT_ERROR: 1
  CONFIG_NEWLIB_STUB: 1
  CONFIG_NO_OTA_UPGRADE: 0
  CONFIG_OTA_NO_DIFF: 1
  CONFIG_PARITION_NO_VERIFY: 0
  CONFIG_NOT_SUPORRT_SASC: 1
  CONFIG_TB_KP: 1
  CONFIG_KP_BUFFER_LEN: 4096
  CONFIG_KEY_MGR_KP_PROTECT: 1
  CONFIG_IMG_AUTHENTICITY_NOT_CHECK: 0
  # CONFIG_SHOW_KEY_IN_KP: y
  CONFIG_MANTB_VERSION: 4
  CONFIG_ARCH_INTERRUPTSTACK: 16384

  #sec_crypto
  CONFIG_SEC_CRYPTO_AES_SW: 1
  CONFIG_SEC_CRYPTO_SHA_SW: 1
  CONFIG_SEC_CRYPTO_RSA_SW: 1
  CONFIG_SEC_CRYPTO_RNG_SW: 1

  CONFIG_MLIBC_PATH: stdio2

  CONFIG_SUNXI_SPI_CPU_XFER_ONLY: 1 # SPI not DMA

  CONFIG_SYSTICK_HZ: 100
  CONFIG_CHIP_D1: 1
  CONFIG_MELIS_LIB_SUB_PATH: "boot"
